import {
  Accessibility, Activity, Airplay, AlarmClock, AlarmClockCheck, AlarmClockOff, AlarmClockPlus,
  AlertCircle, AlertOctagon, AlertTriangle, Album, Ambulance, Anchor, Angry, Annoyed, Apple,
  Archive, Armchair, ArrowDown, ArrowDownLeft, ArrowDownRight, ArrowLeft, ArrowRight, ArrowUp,
  ArrowUpLeft, ArrowUpRight, AtSign, Atom, Award, Axe, Baby, Backpack, BadgePercent, Banana,
  Bandage, Banknote, BarChart3, Bath, Battery, BatteryCharging, BatteryFull, BatteryLow,
  BatteryMedium, BatteryWarning, Beaker, Bed, BedDouble, BedSingle, Beef, Beer, BeerOff, Bell,
  BellDot, BellMinus, BellOff, BellPlus, BellRing, Bike, Binoculars, Bird, Bitcoin, Bluetooth,
  BluetoothOff, Bone, BookA, BookCheck, BookHeart, BookKey, BookMarked, BookMinus, BookOpen,
  BookPlus, BookText, BookX, Bookmark, BookmarkCheck, BookmarkMinus, BookmarkPlus, BookmarkX,
  Boxes, Brain, Briefcase, Brush, Bug, Building, Building2, Bus, Cable, Cake, Calculator,
  Calendar, CalendarCheck, CalendarClock, CalendarDays, CalendarHeart, CalendarMinus,
  CalendarPlus, CalendarRange, CalendarSearch, CalendarX, Camera, Candy, CandyCane, Car,
  Caravan, Carrot, Cast, Cat, ChartArea, ChartBar, ChartCandlestick,
  ChartColumn, ChartLine, ChartPie, ChefHat, Cherry, ChevronDown, ChevronLeft, ChevronRight,
  ChevronUp, Cigarette, Citrus, Clapperboard, ClipboardCheck, ClipboardList, Clock, Clover,
  Cloud, CloudDownload, CloudDrizzle, CloudFog, CloudHail, CloudLightning, CloudMoon, CloudOff,
  CloudRain, CloudRainWind, CloudSnow, CloudSun, CloudUpload, Code2, Codepen, Coffee, Cog,
  Coins, Compass, Construction, Contact, Cookie, CookingPot, CornerUpLeft, CornerUpRight, Cpu,
  CreditCard, Croissant, Cross, Crosshair, Crown, CupSoda, Database, Diamond, Disc, Disc3, Dna,
  Dog, Donut, DoorClosed, DoorOpen, Drama, Drill, Droplet, Droplets, Drum, Drumstick, Dumbbell,
  Ear, EarOff, Eclipse, Egg, Eraser, Euro, Eye, EyeOff, Feather, File, FileAudio, FileCheck,
  FileCode, FileHeart, FileImage, FileLock, FileMinus, FilePen, FilePlus, FileSearch,
  FileSpreadsheet, FileText, FileVideo, FileWarning, FileX, Files, Film, Fingerprint,
  Fish, Flag, Flame, FlaskConical, FlipHorizontal, FlipVertical, Flower, Flower2,
  Focus, Folder, FolderArchive, FolderHeart, FolderLock, FolderOpen, FolderPlus, FolderSearch,
  FolderTree, Footprints, Forward, Frown, Fuel, Gamepad2, Gauge, Gem, Gift, GitBranch,
  GitCommitHorizontal, GitFork, GitMerge, GitPullRequest, Github, Gitlab, GlassWater, Glasses,
  Globe, Globe2, Goal, GraduationCap, Grape, Guitar, Ham, Hammer, Hand, HandCoins, HandHeart,
  HandHelping, HandMetal, HandPlatter, Handshake, HardDrive, HardHat, Hash, Haze, Headphones,
  Heart, HeartHandshake, HeartPulse, HelpCircle, Highlighter, History, Home, Hospital,
  Hourglass, IceCream, Image, IndianRupee, Inbox, Infinity, Info, JapaneseYen, Joystick,
  Key, KeyRound, KeySquare, Keyboard, Lamp, LampCeiling, LampDesk, LampFloor, Landmark,
  Languages, Laptop, Laugh, Leaf, LeafyGreen, Library, Lightbulb, Link, ListChecks, ListFilter,
  ListMinus, ListOrdered, ListPlus, ListTodo, ListX, Lock, LockKeyhole, Lollipop, Luggage,
  Magnet, Mail, Map as MapIcon, MapPin, MapPinned, Martini, Medal, Meh, MemoryStick, MessageCircle,
  MessageCircleHeart, MessageCircleMore, MessageCircleQuestion, MessageSquare, MessagesSquare,
  Mic, Mic2, Microscope, Microwave, Milestone, Milk, MilkOff, Monitor, Moon, Mountain,
  MountainSnow, Mouse, MousePointer, Move, MoveHorizontal, MoveVertical, Music, Music2,
  Music3, Music4, Navigation, NavigationOff, Network, Newspaper, Notebook, NotebookPen,
  NotebookTabs, NotebookText, Orbit, Package, Palette, Paperclip, ParkingCircle,
  ParkingSquare, PartyPopper, PawPrint, Pen, PenLine, PenTool, Pencil, PencilRuler, Percent,
  PersonStanding, Phone, PhoneCall, PhoneIncoming, PhoneOff, PhoneOutgoing, Piano, Pickaxe,
  PiggyBank, Pill, Pin, Pizza, Plane, Plug, Pointer, Popcorn, Power, PowerOff, Printer,
  Puzzle, Rabbit, Radio, Rainbow, Rat, Receipt, Recycle, RefreshCcw, RefreshCw, Reply,
  Ribbon, Rocket, RotateCcw, RotateCw, Route, Rss, Ruler, Sailboat, Salad, Sandwich, Save,
  Scale, ScanFace, School, Scissors, ScreenShare, ScrollText, Search, Send,
  SendHorizontal, Server, ServerOff, Settings, Settings2, Share2, Shield, ShieldAlert,
  ShieldCheck, ShieldOff, ShieldX, Ship, ShoppingBag, ShoppingBasket, ShoppingCart, ShowerHead,
  Shovel, Shrub, Sigma, Skull, Slack, Smartphone, Smile, Snail, Snowflake, Sofa, Soup, Speaker,
  Sparkles, Sprout, Square, Star, Sticker, StickyNote, Stethoscope, Sun, Sunrise, Sunset,
  Syringe, Tablet, Tag, Tags, Target, Telescope, Tent, Terminal, TestTube, TestTubes,
  Theater, Thermometer, ThermometerSnowflake, ThermometerSun, Ticket, Timer, Toilet, Tornado,
  Train, TramFront, TreeDeciduous, TreePalm, TreePine, TrendingDown, TrendingUp, Trophy,
  Truck, Turtle, Tv, Umbrella, Undo, Unlock, Upload, Usb, User, UserCheck, UserCog, UserMinus,
  UserPlus, UserRoundX, UserX, Users, Utensils, Variable, Vault, Vegan, Video, Voicemail,
  Volleyball, Volume, Volume1, Volume2, VolumeX, Wallet, Wand2, WashingMachine, Watch, Waves,
  Wheat, WheatOff, Wifi, WifiOff, Wind, Wine, WineOff, Workflow, Worm, Wrench, X, Zap,
  DollarSign, Megaphone,
  type LucideIcon,
} from 'lucide-react';

interface IconEntry {
  name: string;
  Icon: LucideIcon;
  /** Lowercase keywords used by search + suggestions. Name itself is always included. */
  tags: string[];
}

/** Curated whitelist. Order matters for tie-breaking in suggestions. */
const ENTRIES: IconEntry[] = [
  { name: 'Activity', Icon: Activity, tags: ['pulse', 'health', 'heart', 'fitness'] },
  { name: 'AlarmClock', Icon: AlarmClock, tags: ['alarm', 'wake', 'time'] },
  { name: 'Apple', Icon: Apple, tags: ['fruit', 'food', 'snack'] },
  { name: 'Archive', Icon: Archive, tags: ['box', 'storage'] },
  { name: 'Award', Icon: Award, tags: ['medal', 'prize', 'win'] },
  { name: 'Baby', Icon: Baby, tags: ['child', 'kid', 'parent', 'family'] },
  { name: 'Banknote', Icon: Banknote, tags: ['money', 'cash', 'finance'] },
  { name: 'BarChart', Icon: BarChart3, tags: ['analytics', 'stats', 'metrics', 'chart'] },
  { name: 'Beaker', Icon: Beaker, tags: ['lab', 'science', 'experiment'] },
  { name: 'Bed', Icon: Bed, tags: ['sleep', 'rest', 'nap'] },
  { name: 'Bell', Icon: Bell, tags: ['alert', 'notification', 'reminder'] },
  { name: 'Bike', Icon: Bike, tags: ['cycle', 'ride', 'commute', 'sport'] },
  { name: 'BookOpen', Icon: BookOpen, tags: ['read', 'book', 'study', 'learn'] },
  { name: 'Bookmark', Icon: Bookmark, tags: ['save', 'mark'] },
  { name: 'Briefcase', Icon: Briefcase, tags: ['work', 'job', 'office', 'business'] },
  { name: 'Brush', Icon: Brush, tags: ['paint', 'art', 'design', 'draw'] },
  { name: 'Bug', Icon: Bug, tags: ['debug', 'issue', 'fix'] },
  { name: 'Building', Icon: Building2, tags: ['office', 'company', 'corporate'] },
  { name: 'Cake', Icon: Cake, tags: ['birthday', 'dessert', 'celebrate'] },
  { name: 'Calculator', Icon: Calculator, tags: ['math', 'finance', 'numbers'] },
  { name: 'Calendar', Icon: Calendar, tags: ['date', 'schedule', 'event'] },
  { name: 'Camera', Icon: Camera, tags: ['photo', 'picture', 'shoot'] },
  { name: 'Car', Icon: Car, tags: ['drive', 'vehicle', 'commute'] },
  { name: 'Carrot', Icon: Carrot, tags: ['veggie', 'food', 'cook'] },
  { name: 'ChartLine', Icon: ChartLine, tags: ['growth', 'trend', 'metric'] },
  { name: 'Cherry', Icon: Cherry, tags: ['fruit', 'snack'] },
  { name: 'ChefHat', Icon: ChefHat, tags: ['cook', 'kitchen', 'food', 'recipe'] },
  { name: 'Cigarette', Icon: Cigarette, tags: ['smoke', 'break'] },
  { name: 'Clapperboard', Icon: Clapperboard, tags: ['film', 'movie', 'video', 'shoot'] },
  { name: 'Clipboard', Icon: ClipboardList, tags: ['list', 'todo', 'task', 'checklist'] },
  { name: 'Cloud', Icon: Cloud, tags: ['weather', 'sync', 'storage'] },
  { name: 'Code', Icon: Code2, tags: ['dev', 'program', 'engineering', 'ship'] },
  { name: 'Coffee', Icon: Coffee, tags: ['drink', 'break', 'cafe', 'morning'] },
  { name: 'Compass', Icon: Compass, tags: ['navigate', 'direction', 'explore'] },
  { name: 'Cpu', Icon: Cpu, tags: ['computer', 'hardware', 'tech'] },
  { name: 'CreditCard', Icon: CreditCard, tags: ['pay', 'finance', 'card', 'bill'] },
  { name: 'Croissant', Icon: Croissant, tags: ['bakery', 'breakfast', 'food'] },
  { name: 'Crown', Icon: Crown, tags: ['premium', 'royal', 'priority'] },
  { name: 'Database', Icon: Database, tags: ['data', 'storage', 'sql'] },
  { name: 'Dollar', Icon: DollarSign, tags: ['money', 'finance', 'pay'] },
  { name: 'Dog', Icon: Dog, tags: ['pet', 'walk', 'animal'] },
  { name: 'Dumbbell', Icon: Dumbbell, tags: ['gym', 'workout', 'lift', 'fitness', 'strength'] },
  { name: 'Egg', Icon: Egg, tags: ['breakfast', 'cook', 'food'] },
  { name: 'Feather', Icon: Feather, tags: ['light', 'write', 'quill'] },
  { name: 'Film', Icon: Film, tags: ['movie', 'video', 'cinema', 'edit'] },
  { name: 'Flag', Icon: Flag, tags: ['goal', 'milestone', 'finish'] },
  { name: 'Flame', Icon: Flame, tags: ['streak', 'hot', 'fire', 'energy'] },
  { name: 'Flask', Icon: FlaskConical, tags: ['lab', 'science', 'chem'] },
  { name: 'Flower', Icon: Flower2, tags: ['garden', 'plant', 'nature'] },
  { name: 'Folder', Icon: Folder, tags: ['file', 'organize', 'project'] },
  { name: 'Footprints', Icon: Footprints, tags: ['walk', 'stroll', 'step', 'hike'] },
  { name: 'Gamepad', Icon: Gamepad2, tags: ['game', 'play', 'console'] },
  { name: 'Gauge', Icon: Gauge, tags: ['speed', 'meter', 'measure'] },
  { name: 'Graduation', Icon: GraduationCap, tags: ['school', 'study', 'learn', 'edu'] },
  { name: 'Guitar', Icon: Guitar, tags: ['music', 'practice', 'instrument'] },
  { name: 'Hammer', Icon: Hammer, tags: ['build', 'fix', 'tool', 'repair'] },
  { name: 'Hand', Icon: Hand, tags: ['wave', 'hello', 'stop'] },
  { name: 'Headphones', Icon: Headphones, tags: ['music', 'listen', 'audio', 'podcast'] },
  { name: 'Heart', Icon: Heart, tags: ['love', 'favorite', 'like'] },
  { name: 'HeartHandshake', Icon: HeartHandshake, tags: ['wedding', 'engage', 'anniversary', 'love', 'date'] },
  { name: 'Home', Icon: Home, tags: ['house', 'clean', 'laundry', 'chore'] },
  { name: 'IceCream', Icon: IceCream, tags: ['dessert', 'sweet', 'snack'] },
  { name: 'Image', Icon: Image, tags: ['photo', 'picture'] },
  { name: 'Inbox', Icon: Inbox, tags: ['mail', 'email', 'messages'] },
  { name: 'Key', Icon: Key, tags: ['unlock', 'access', 'auth'] },
  { name: 'Lamp', Icon: Lamp, tags: ['light', 'desk'] },
  { name: 'Languages', Icon: Languages, tags: ['translate', 'learn', 'language'] },
  { name: 'Laptop', Icon: Laptop, tags: ['computer', 'work', 'remote'] },
  { name: 'Leaf', Icon: Leaf, tags: ['nature', 'plant', 'eco'] },
  { name: 'Library', Icon: Library, tags: ['books', 'study', 'read'] },
  { name: 'Lightbulb', Icon: Lightbulb, tags: ['idea', 'brainstorm', 'think'] },
  { name: 'Link', Icon: Link, tags: ['url', 'connect'] },
  { name: 'Location', Icon: MapPin, tags: ['place', 'pin', 'travel'] },
  { name: 'Mail', Icon: Mail, tags: ['email', 'inbox', 'message'] },
  { name: 'Martini', Icon: Martini, tags: ['drink', 'bar', 'happy', 'cocktail'] },
  { name: 'Megaphone', Icon: Megaphone, tags: ['announce', 'marketing', 'promo'] },
  { name: 'Message', Icon: MessageCircle, tags: ['chat', 'talk', 'sms', 'text'] },
  { name: 'Mic', Icon: Mic, tags: ['record', 'voice', 'podcast', 'talk'] },
  { name: 'Moon', Icon: Moon, tags: ['night', 'sleep', 'dark'] },
  { name: 'Mountain', Icon: Mountain, tags: ['hike', 'outdoor', 'nature'] },
  { name: 'Music', Icon: Music, tags: ['song', 'audio', 'practice'] },
  { name: 'Newspaper', Icon: Newspaper, tags: ['news', 'read', 'press'] },
  { name: 'Notebook', Icon: Notebook, tags: ['journal', 'notes', 'write'] },
  { name: 'Package', Icon: Package, tags: ['ship', 'box', 'delivery'] },
  { name: 'Palette', Icon: Palette, tags: ['art', 'color', 'design'] },
  { name: 'Party', Icon: PartyPopper, tags: ['celebrate', 'event'] },
  { name: 'Paw', Icon: PawPrint, tags: ['pet', 'animal', 'vet'] },
  { name: 'Pen', Icon: PenLine, tags: ['write', 'draft', 'journal', 'note'] },
  { name: 'PenTool', Icon: PenTool, tags: ['design', 'sketch', 'vector'] },
  { name: 'Phone', Icon: Phone, tags: ['call', 'ring', 'mobile'] },
  { name: 'PiggyBank', Icon: PiggyBank, tags: ['save', 'money', 'budget'] },
  { name: 'Pill', Icon: Pill, tags: ['medicine', 'health', 'meds'] },
  { name: 'Pin', Icon: Pin, tags: ['mark', 'fix'] },
  { name: 'Pizza', Icon: Pizza, tags: ['food', 'dinner'] },
  { name: 'Plane', Icon: Plane, tags: ['travel', 'trip', 'flight', 'airport'] },
  { name: 'Plug', Icon: Plug, tags: ['power', 'charge', 'connect'] },
  { name: 'Printer', Icon: Printer, tags: ['print', 'paper'] },
  { name: 'Puzzle', Icon: Puzzle, tags: ['problem', 'solve', 'piece'] },
  { name: 'Receipt', Icon: Receipt, tags: ['bill', 'expense', 'invoice'] },
  { name: 'Recycle', Icon: Recycle, tags: ['eco', 'reuse'] },
  { name: 'Rocket', Icon: Rocket, tags: ['launch', 'ship', 'start', 'fast'] },
  { name: 'Ruler', Icon: Ruler, tags: ['measure', 'design'] },
  { name: 'Scale', Icon: Scale, tags: ['balance', 'law', 'weigh'] },
  { name: 'Scissors', Icon: Scissors, tags: ['cut', 'trim'] },
  { name: 'Scroll', Icon: ScrollText, tags: ['document', 'doc', 'note'] },
  { name: 'Search', Icon: Search, tags: ['find', 'research', 'look'] },
  { name: 'Settings', Icon: Settings, tags: ['config', 'options'] },
  { name: 'Share', Icon: Share2, tags: ['send', 'post'] },
  { name: 'Shield', Icon: Shield, tags: ['secure', 'safe', 'protect'] },
  { name: 'ShoppingBag', Icon: ShoppingBag, tags: ['shop', 'errand', 'buy'] },
  { name: 'ShoppingCart', Icon: ShoppingCart, tags: ['shop', 'errand', 'buy', 'grocery'] },
  { name: 'Shovel', Icon: Shovel, tags: ['dig', 'garden', 'work'] },
  { name: 'Shrub', Icon: Shrub, tags: ['garden', 'plant'] },
  { name: 'Smile', Icon: Smile, tags: ['happy', 'mood', 'face'] },
  { name: 'Sparkles', Icon: Sparkles, tags: ['idea', 'magic', 'create', 'brainstorm', 'new'] },
  { name: 'Sprout', Icon: Sprout, tags: ['grow', 'plant', 'start'] },
  { name: 'Star', Icon: Star, tags: ['favorite', 'rate'] },
  { name: 'Sun', Icon: Sun, tags: ['morning', 'bright', 'weather'] },
  { name: 'Sunrise', Icon: Sunrise, tags: ['morning', 'early', 'dawn'] },
  { name: 'Sunset', Icon: Sunset, tags: ['evening', 'dusk'] },
  { name: 'Target', Icon: Target, tags: ['goal', 'focus', 'aim'] },
  { name: 'Tent', Icon: Tent, tags: ['camp', 'outdoor'] },
  { name: 'Terminal', Icon: Terminal, tags: ['code', 'dev', 'cli', 'shell'] },
  { name: 'Ticket', Icon: Ticket, tags: ['event', 'show', 'concert'] },
  { name: 'Timer', Icon: Timer, tags: ['stopwatch', 'pomodoro', 'focus'] },
  { name: 'Train', Icon: Train, tags: ['commute', 'travel'] },
  { name: 'Tree', Icon: TreePine, tags: ['nature', 'outdoor', 'park'] },
  { name: 'Trending', Icon: TrendingUp, tags: ['growth', 'analytics', 'metric'] },
  { name: 'Trophy', Icon: Trophy, tags: ['win', 'award', 'goal'] },
  { name: 'Truck', Icon: Truck, tags: ['delivery', 'ship', 'move'] },
  { name: 'Tv', Icon: Tv, tags: ['watch', 'show', 'media'] },
  { name: 'Umbrella', Icon: Umbrella, tags: ['rain', 'weather'] },
  { name: 'User', Icon: User, tags: ['profile', 'person', 'account'] },
  { name: 'Users', Icon: Users, tags: ['meet', 'standup', 'sync', 'team', 'interview', 'meeting', 'group'] },
  { name: 'Utensils', Icon: Utensils, tags: ['lunch', 'dinner', 'breakfast', 'eat', 'food', 'meal'] },
  { name: 'Video', Icon: Video, tags: ['call', 'zoom', 'meeting', 'record'] },
  { name: 'Wallet', Icon: Wallet, tags: ['money', 'finance', 'budget'] },
  { name: 'Wand', Icon: Wand2, tags: ['magic', 'create', 'auto'] },
  { name: 'Watch', Icon: Watch, tags: ['time', 'wear'] },
  { name: 'Waves', Icon: Waves, tags: ['ocean', 'beach', 'flow'] },
  { name: 'Wrench', Icon: Wrench, tags: ['fix', 'repair', 'tool', 'maintenance'] },
  { name: 'Zap', Icon: Zap, tags: ['energy', 'fast', 'quick', 'action'] },

  // ─── People & social ───────────────────────────────
  { name: 'UserCheck', Icon: UserCheck, tags: ['verified', 'approved', 'confirm', 'person'] },
  { name: 'UserPlus', Icon: UserPlus, tags: ['add', 'invite', 'new', 'person'] },
  { name: 'UserMinus', Icon: UserMinus, tags: ['remove', 'person'] },
  { name: 'UserX', Icon: UserX, tags: ['remove', 'block', 'person'] },
  { name: 'UserRoundX', Icon: UserRoundX, tags: ['remove', 'block', 'person'] },
  { name: 'UserCog', Icon: UserCog, tags: ['settings', 'profile', 'person'] },
  { name: 'Contact', Icon: Contact, tags: ['address', 'card', 'person'] },
  { name: 'Handshake', Icon: Handshake, tags: ['deal', 'agreement', 'meeting', 'partner'] },
  { name: 'PersonStanding', Icon: PersonStanding, tags: ['person', 'accessibility'] },
  { name: 'Accessibility', Icon: Accessibility, tags: ['access', 'disability', 'a11y'] },

  // ─── Body & expressions ─────────────────────────────
  { name: 'Brain', Icon: Brain, tags: ['mind', 'think', 'study', 'focus', 'memory'] },
  { name: 'Eye', Icon: Eye, tags: ['look', 'see', 'view', 'watch'] },
  { name: 'EyeOff', Icon: EyeOff, tags: ['hide', 'invisible', 'private'] },
  { name: 'Ear', Icon: Ear, tags: ['listen', 'hear', 'audio'] },
  { name: 'EarOff', Icon: EarOff, tags: ['mute', 'silence'] },
  { name: 'Glasses', Icon: Glasses, tags: ['vision', 'read', 'eyewear'] },
  { name: 'HandHeart', Icon: HandHeart, tags: ['care', 'give', 'charity', 'donate'] },
  { name: 'HandMetal', Icon: HandMetal, tags: ['rock', 'cool', 'gesture'] },
  { name: 'HandHelping', Icon: HandHelping, tags: ['help', 'support', 'assist'] },
  { name: 'Frown', Icon: Frown, tags: ['sad', 'mood', 'face'] },
  { name: 'Meh', Icon: Meh, tags: ['neutral', 'mood', 'face'] },
  { name: 'Angry', Icon: Angry, tags: ['mad', 'mood', 'face'] },
  { name: 'Annoyed', Icon: Annoyed, tags: ['frustrated', 'mood', 'face'] },
  { name: 'Laugh', Icon: Laugh, tags: ['happy', 'mood', 'face', 'joy'] },
  { name: 'Skull', Icon: Skull, tags: ['death', 'danger', 'halloween'] },

  // ─── Health & medical ─────────────────────────────
  { name: 'Stethoscope', Icon: Stethoscope, tags: ['doctor', 'health', 'medical', 'appointment'] },
  { name: 'Syringe', Icon: Syringe, tags: ['shot', 'vaccine', 'medical', 'inject'] },
  { name: 'Bandage', Icon: Bandage, tags: ['injury', 'heal', 'medical', 'first-aid'] },
  { name: 'Thermometer', Icon: Thermometer, tags: ['temperature', 'fever', 'sick', 'health'] },
  { name: 'ThermometerSnowflake', Icon: ThermometerSnowflake, tags: ['cold', 'temperature'] },
  { name: 'ThermometerSun', Icon: ThermometerSun, tags: ['hot', 'temperature'] },
  { name: 'HeartPulse', Icon: HeartPulse, tags: ['health', 'vitals', 'medical', 'pulse'] },
  { name: 'Cross', Icon: Cross, tags: ['medical', 'health', 'plus'] },
  { name: 'Hospital', Icon: Hospital, tags: ['medical', 'doctor', 'clinic', 'er'] },
  { name: 'Ambulance', Icon: Ambulance, tags: ['emergency', 'medical', 'urgent'] },
  { name: 'Bone', Icon: Bone, tags: ['skeleton', 'orthopedic', 'dog'] },
  { name: 'Dna', Icon: Dna, tags: ['genetics', 'biology', 'science'] },

  // ─── Food & drink ─────────────────────────────────
  { name: 'Wine', Icon: Wine, tags: ['drink', 'alcohol', 'dinner', 'date'] },
  { name: 'WineOff', Icon: WineOff, tags: ['sober', 'no-alcohol'] },
  { name: 'Beer', Icon: Beer, tags: ['drink', 'pub', 'alcohol', 'happy'] },
  { name: 'BeerOff', Icon: BeerOff, tags: ['sober', 'dry'] },
  { name: 'Soup', Icon: Soup, tags: ['lunch', 'food', 'meal'] },
  { name: 'Salad', Icon: Salad, tags: ['healthy', 'food', 'lunch', 'veggie'] },
  { name: 'Sandwich', Icon: Sandwich, tags: ['lunch', 'food', 'meal'] },
  { name: 'Fish', Icon: Fish, tags: ['food', 'seafood', 'pet'] },
  { name: 'Drumstick', Icon: Drumstick, tags: ['chicken', 'food', 'meat', 'dinner'] },
  { name: 'Donut', Icon: Donut, tags: ['dessert', 'snack', 'sweet'] },
  { name: 'Lollipop', Icon: Lollipop, tags: ['candy', 'sweet', 'kids'] },
  { name: 'Popcorn', Icon: Popcorn, tags: ['snack', 'movie', 'cinema'] },
  { name: 'Candy', Icon: Candy, tags: ['sweet', 'treat', 'kids'] },
  { name: 'CandyCane', Icon: CandyCane, tags: ['holiday', 'christmas', 'sweet'] },
  { name: 'CupSoda', Icon: CupSoda, tags: ['drink', 'soda', 'beverage'] },
  { name: 'GlassWater', Icon: GlassWater, tags: ['hydrate', 'drink', 'water'] },
  { name: 'Milk', Icon: Milk, tags: ['dairy', 'drink', 'breakfast'] },
  { name: 'MilkOff', Icon: MilkOff, tags: ['dairy-free', 'lactose'] },
  { name: 'CookingPot', Icon: CookingPot, tags: ['cook', 'kitchen', 'dinner', 'recipe'] },
  { name: 'HandPlatter', Icon: HandPlatter, tags: ['serve', 'food', 'meal'] },
  { name: 'Wheat', Icon: Wheat, tags: ['grain', 'bread', 'farm'] },
  { name: 'WheatOff', Icon: WheatOff, tags: ['gluten-free', 'no-wheat'] },
  { name: 'Cookie', Icon: Cookie, tags: ['snack', 'sweet', 'dessert'] },
  { name: 'Beef', Icon: Beef, tags: ['meat', 'dinner', 'food'] },
  { name: 'Ham', Icon: Ham, tags: ['meat', 'breakfast', 'food'] },
  { name: 'Citrus', Icon: Citrus, tags: ['fruit', 'lemon', 'orange'] },
  { name: 'Grape', Icon: Grape, tags: ['fruit', 'wine'] },
  { name: 'Banana', Icon: Banana, tags: ['fruit', 'snack'] },
  { name: 'Vegan', Icon: Vegan, tags: ['plant', 'diet', 'food'] },

  // ─── Weather ──────────────────────────────────────
  { name: 'CloudRain', Icon: CloudRain, tags: ['weather', 'rainy'] },
  { name: 'CloudDrizzle', Icon: CloudDrizzle, tags: ['weather', 'rain', 'light'] },
  { name: 'CloudSnow', Icon: CloudSnow, tags: ['weather', 'winter', 'snowy'] },
  { name: 'CloudLightning', Icon: CloudLightning, tags: ['weather', 'storm', 'thunder'] },
  { name: 'CloudFog', Icon: CloudFog, tags: ['weather', 'foggy', 'mist'] },
  { name: 'CloudHail', Icon: CloudHail, tags: ['weather', 'hail'] },
  { name: 'CloudSun', Icon: CloudSun, tags: ['weather', 'partly-sunny'] },
  { name: 'CloudMoon', Icon: CloudMoon, tags: ['weather', 'night'] },
  { name: 'CloudRainWind', Icon: CloudRainWind, tags: ['weather', 'storm', 'rain'] },
  { name: 'CloudOff', Icon: CloudOff, tags: ['offline', 'no-cloud'] },
  { name: 'CloudUpload', Icon: CloudUpload, tags: ['upload', 'sync', 'backup'] },
  { name: 'CloudDownload', Icon: CloudDownload, tags: ['download', 'sync'] },
  { name: 'Snowflake', Icon: Snowflake, tags: ['cold', 'winter', 'frost'] },
  { name: 'Wind', Icon: Wind, tags: ['breeze', 'air', 'weather'] },
  { name: 'Rainbow', Icon: Rainbow, tags: ['pride', 'colorful', 'after-rain'] },
  { name: 'Droplet', Icon: Droplet, tags: ['water', 'drop', 'liquid'] },
  { name: 'Droplets', Icon: Droplets, tags: ['water', 'humidity', 'liquid'] },
  { name: 'Tornado', Icon: Tornado, tags: ['storm', 'wind', 'weather'] },
  { name: 'Haze', Icon: Haze, tags: ['weather', 'fog', 'smog'] },
  { name: 'Eclipse', Icon: Eclipse, tags: ['moon', 'sun', 'astronomy'] },
  { name: 'Orbit', Icon: Orbit, tags: ['space', 'planet', 'satellite'] },

  // ─── Animals ──────────────────────────────────────
  { name: 'Bird', Icon: Bird, tags: ['animal', 'pet'] },
  { name: 'Cat', Icon: Cat, tags: ['pet', 'animal'] },
  { name: 'Rabbit', Icon: Rabbit, tags: ['pet', 'animal', 'bunny'] },
  { name: 'Rat', Icon: Rat, tags: ['rodent', 'pest', 'animal'] },
  { name: 'Turtle', Icon: Turtle, tags: ['slow', 'animal', 'pet'] },
  { name: 'Snail', Icon: Snail, tags: ['slow', 'animal'] },
  { name: 'Worm', Icon: Worm, tags: ['animal', 'garden'] },

  // ─── Plants & nature ──────────────────────────────
  { name: 'TreeDeciduous', Icon: TreeDeciduous, tags: ['nature', 'park', 'tree'] },
  { name: 'TreePalm', Icon: TreePalm, tags: ['beach', 'tropical', 'vacation'] },
  { name: 'Flower', Icon: Flower, tags: ['garden', 'plant', 'bloom'] },
  { name: 'LeafyGreen', Icon: LeafyGreen, tags: ['veggie', 'plant', 'healthy'] },
  { name: 'Clover', Icon: Clover, tags: ['luck', 'nature', 'irish'] },

  // ─── Productivity & dev ───────────────────────────
  { name: 'GitBranch', Icon: GitBranch, tags: ['dev', 'git', 'branch', 'code'] },
  { name: 'GitCommit', Icon: GitCommitHorizontal, tags: ['dev', 'git', 'commit', 'code'] },
  { name: 'GitMerge', Icon: GitMerge, tags: ['dev', 'git', 'merge'] },
  { name: 'GitPullRequest', Icon: GitPullRequest, tags: ['dev', 'git', 'pr', 'review'] },
  { name: 'GitFork', Icon: GitFork, tags: ['dev', 'git', 'fork'] },
  { name: 'Github', Icon: Github, tags: ['dev', 'repo', 'code'] },
  { name: 'Gitlab', Icon: Gitlab, tags: ['dev', 'repo', 'code'] },
  { name: 'Codepen', Icon: Codepen, tags: ['dev', 'frontend', 'demo'] },
  { name: 'Slack', Icon: Slack, tags: ['chat', 'team', 'work'] },
  { name: 'File', Icon: File, tags: ['document', 'doc'] },
  { name: 'FileText', Icon: FileText, tags: ['document', 'doc', 'note'] },
  { name: 'FilePen', Icon: FilePen, tags: ['edit', 'document', 'write'] },
  { name: 'FileCheck', Icon: FileCheck, tags: ['done', 'approved', 'document'] },
  { name: 'FilePlus', Icon: FilePlus, tags: ['new', 'add', 'document'] },
  { name: 'FileMinus', Icon: FileMinus, tags: ['remove', 'document'] },
  { name: 'FileX', Icon: FileX, tags: ['delete', 'document'] },
  { name: 'FileSearch', Icon: FileSearch, tags: ['find', 'document'] },
  { name: 'FileCode', Icon: FileCode, tags: ['dev', 'code', 'document'] },
  { name: 'FileLock', Icon: FileLock, tags: ['secure', 'private', 'document'] },
  { name: 'FileHeart', Icon: FileHeart, tags: ['favorite', 'document'] },
  { name: 'FileImage', Icon: FileImage, tags: ['photo', 'picture', 'document'] },
  { name: 'FileVideo', Icon: FileVideo, tags: ['movie', 'document'] },
  { name: 'FileAudio', Icon: FileAudio, tags: ['sound', 'music', 'document'] },
  { name: 'FileWarning', Icon: FileWarning, tags: ['alert', 'document', 'issue'] },
  { name: 'FileSpreadsheet', Icon: FileSpreadsheet, tags: ['excel', 'data', 'sheet'] },
  { name: 'Files', Icon: Files, tags: ['documents', 'multiple'] },
  { name: 'FolderOpen', Icon: FolderOpen, tags: ['files', 'organize'] },
  { name: 'FolderPlus', Icon: FolderPlus, tags: ['new', 'add', 'folder'] },
  { name: 'FolderHeart', Icon: FolderHeart, tags: ['favorite', 'folder'] },
  { name: 'FolderLock', Icon: FolderLock, tags: ['secure', 'folder'] },
  { name: 'FolderSearch', Icon: FolderSearch, tags: ['find', 'folder'] },
  { name: 'FolderTree', Icon: FolderTree, tags: ['hierarchy', 'structure'] },
  { name: 'FolderArchive', Icon: FolderArchive, tags: ['old', 'storage'] },
  { name: 'ListTodo', Icon: ListTodo, tags: ['tasks', 'todo', 'checklist'] },
  { name: 'ListChecks', Icon: ListChecks, tags: ['done', 'checklist', 'tasks'] },
  { name: 'ListOrdered', Icon: ListOrdered, tags: ['numbered', 'list'] },
  { name: 'ListPlus', Icon: ListPlus, tags: ['add', 'list'] },
  { name: 'ListMinus', Icon: ListMinus, tags: ['remove', 'list'] },
  { name: 'ListX', Icon: ListX, tags: ['delete', 'list'] },
  { name: 'ListFilter', Icon: ListFilter, tags: ['sort', 'filter', 'list'] },
  { name: 'Workflow', Icon: Workflow, tags: ['process', 'flow', 'pipeline'] },
  { name: 'Network', Icon: Network, tags: ['connected', 'graph', 'system'] },
  { name: 'ClipboardCheck', Icon: ClipboardCheck, tags: ['done', 'tasks', 'checklist'] },
  { name: 'Boxes', Icon: Boxes, tags: ['storage', 'organize', 'stack'] },

  // ─── Travel & transport ──────────────────────────
  { name: 'Ship', Icon: Ship, tags: ['boat', 'travel', 'cargo'] },
  { name: 'Sailboat', Icon: Sailboat, tags: ['boat', 'sea', 'sail'] },
  { name: 'Bus', Icon: Bus, tags: ['transit', 'commute', 'travel'] },
  { name: 'TramFront', Icon: TramFront, tags: ['transit', 'tram', 'commute'] },
  { name: 'Luggage', Icon: Luggage, tags: ['travel', 'suitcase', 'trip'] },
  { name: 'Map', Icon: MapIcon, tags: ['navigate', 'travel', 'explore'] },
  { name: 'MapPinned', Icon: MapPinned, tags: ['location', 'place'] },
  { name: 'Globe', Icon: Globe, tags: ['world', 'earth', 'international'] },
  { name: 'Globe2', Icon: Globe2, tags: ['world', 'earth'] },
  { name: 'Backpack', Icon: Backpack, tags: ['hike', 'school', 'travel', 'bag'] },
  { name: 'Anchor', Icon: Anchor, tags: ['ship', 'sea', 'stop'] },
  { name: 'Fuel', Icon: Fuel, tags: ['gas', 'energy', 'car'] },
  { name: 'Caravan', Icon: Caravan, tags: ['camp', 'rv', 'travel'] },
  { name: 'Navigation', Icon: Navigation, tags: ['direction', 'gps'] },
  { name: 'NavigationOff', Icon: NavigationOff, tags: ['no-gps', 'offline'] },
  { name: 'Route', Icon: Route, tags: ['path', 'navigation', 'plan'] },
  { name: 'Milestone', Icon: Milestone, tags: ['progress', 'marker', 'goal'] },
  { name: 'ParkingCircle', Icon: ParkingCircle, tags: ['park', 'car', 'lot'] },
  { name: 'ParkingSquare', Icon: ParkingSquare, tags: ['park', 'car', 'lot'] },

  // ─── Money & commerce ────────────────────────────
  { name: 'Coins', Icon: Coins, tags: ['money', 'cash', 'currency'] },
  { name: 'HandCoins', Icon: HandCoins, tags: ['donate', 'give', 'money'] },
  { name: 'Landmark', Icon: Landmark, tags: ['bank', 'government', 'finance'] },
  { name: 'BadgePercent', Icon: BadgePercent, tags: ['discount', 'sale', 'offer'] },
  { name: 'Percent', Icon: Percent, tags: ['discount', 'rate', 'math'] },
  { name: 'Euro', Icon: Euro, tags: ['money', 'currency'] },
  { name: 'JapaneseYen', Icon: JapaneseYen, tags: ['money', 'yen', 'currency'] },
  { name: 'IndianRupee', Icon: IndianRupee, tags: ['money', 'rupee', 'currency'] },
  { name: 'Bitcoin', Icon: Bitcoin, tags: ['crypto', 'btc', 'currency'] },
  { name: 'TrendingDown', Icon: TrendingDown, tags: ['decline', 'loss', 'metric'] },
  { name: 'ChartPie', Icon: ChartPie, tags: ['analytics', 'breakdown'] },
  { name: 'ChartArea', Icon: ChartArea, tags: ['analytics', 'trend'] },
  { name: 'ChartBar', Icon: ChartBar, tags: ['analytics', 'stats'] },
  { name: 'ChartColumn', Icon: ChartColumn, tags: ['analytics', 'stats'] },
  { name: 'ChartCandlestick', Icon: ChartCandlestick, tags: ['stocks', 'trading', 'finance'] },
  { name: 'ShoppingBasket', Icon: ShoppingBasket, tags: ['shop', 'buy', 'cart'] },
  { name: 'DollarSign', Icon: DollarSign, tags: ['money', 'finance', 'pay'] },

  // ─── Communication ───────────────────────────────
  { name: 'MessageSquare', Icon: MessageSquare, tags: ['chat', 'sms', 'comment'] },
  { name: 'MessagesSquare', Icon: MessagesSquare, tags: ['chat', 'conversations'] },
  { name: 'MessageCircleMore', Icon: MessageCircleMore, tags: ['typing', 'chat'] },
  { name: 'MessageCircleHeart', Icon: MessageCircleHeart, tags: ['love', 'chat'] },
  { name: 'MessageCircleQuestion', Icon: MessageCircleQuestion, tags: ['help', 'question', 'chat'] },
  { name: 'AtSign', Icon: AtSign, tags: ['mention', 'email', 'tag'] },
  { name: 'Send', Icon: Send, tags: ['email', 'message', 'submit'] },
  { name: 'SendHorizontal', Icon: SendHorizontal, tags: ['send', 'submit'] },
  { name: 'Reply', Icon: Reply, tags: ['respond', 'email'] },
  { name: 'Forward', Icon: Forward, tags: ['send-on', 'email'] },
  { name: 'PhoneCall', Icon: PhoneCall, tags: ['call', 'meeting', 'ring'] },
  { name: 'PhoneIncoming', Icon: PhoneIncoming, tags: ['call', 'in'] },
  { name: 'PhoneOutgoing', Icon: PhoneOutgoing, tags: ['call', 'out'] },
  { name: 'PhoneOff', Icon: PhoneOff, tags: ['hangup', 'mute'] },
  { name: 'Voicemail', Icon: Voicemail, tags: ['message', 'recorded'] },
  { name: 'Hash', Icon: Hash, tags: ['tag', 'channel', 'number'] },
  { name: 'BellOff', Icon: BellOff, tags: ['mute', 'silent', 'dnd'] },
  { name: 'BellRing', Icon: BellRing, tags: ['alert', 'notify', 'active'] },
  { name: 'BellPlus', Icon: BellPlus, tags: ['add-notification'] },
  { name: 'BellMinus', Icon: BellMinus, tags: ['remove-notification'] },
  { name: 'BellDot', Icon: BellDot, tags: ['unread', 'notify'] },
  { name: 'Megaphone', Icon: Megaphone, tags: ['announce', 'marketing', 'promo'] },
  { name: 'Volume', Icon: Volume, tags: ['sound', 'audio'] },
  { name: 'Volume1', Icon: Volume1, tags: ['low-volume', 'audio'] },
  { name: 'Volume2', Icon: Volume2, tags: ['high-volume', 'audio'] },
  { name: 'VolumeX', Icon: VolumeX, tags: ['mute', 'silent'] },
  { name: 'Rss', Icon: Rss, tags: ['feed', 'subscribe', 'news'] },

  // ─── Tech & devices ──────────────────────────────
  { name: 'Monitor', Icon: Monitor, tags: ['screen', 'desktop', 'display'] },
  { name: 'Smartphone', Icon: Smartphone, tags: ['phone', 'mobile'] },
  { name: 'Tablet', Icon: Tablet, tags: ['ipad', 'mobile'] },
  { name: 'Server', Icon: Server, tags: ['backend', 'cloud', 'host'] },
  { name: 'ServerOff', Icon: ServerOff, tags: ['down', 'offline'] },
  { name: 'Wifi', Icon: Wifi, tags: ['internet', 'network', 'wireless'] },
  { name: 'WifiOff', Icon: WifiOff, tags: ['offline', 'no-internet'] },
  { name: 'Bluetooth', Icon: Bluetooth, tags: ['wireless', 'pair'] },
  { name: 'BluetoothOff', Icon: BluetoothOff, tags: ['disconnected'] },
  { name: 'Battery', Icon: Battery, tags: ['power', 'charge'] },
  { name: 'BatteryLow', Icon: BatteryLow, tags: ['low-power', 'charge'] },
  { name: 'BatteryMedium', Icon: BatteryMedium, tags: ['half-power'] },
  { name: 'BatteryFull', Icon: BatteryFull, tags: ['full-power'] },
  { name: 'BatteryCharging', Icon: BatteryCharging, tags: ['power-up', 'plug'] },
  { name: 'BatteryWarning', Icon: BatteryWarning, tags: ['low', 'critical'] },
  { name: 'Power', Icon: Power, tags: ['on', 'shutdown', 'turn-off'] },
  { name: 'PowerOff', Icon: PowerOff, tags: ['off', 'shutdown'] },
  { name: 'Cable', Icon: Cable, tags: ['connect', 'wire', 'plug'] },
  { name: 'Usb', Icon: Usb, tags: ['port', 'connect', 'drive'] },
  { name: 'Radio', Icon: Radio, tags: ['audio', 'signal', 'broadcast'] },
  { name: 'ScreenShare', Icon: ScreenShare, tags: ['present', 'meeting', 'share'] },
  { name: 'Cast', Icon: Cast, tags: ['stream', 'mirror', 'tv'] },
  { name: 'Airplay', Icon: Airplay, tags: ['stream', 'mirror', 'apple'] },
  { name: 'Mouse', Icon: Mouse, tags: ['click', 'cursor', 'device'] },
  { name: 'MousePointer', Icon: MousePointer, tags: ['cursor', 'click'] },
  { name: 'Pointer', Icon: Pointer, tags: ['tap', 'click', 'select'] },
  { name: 'Keyboard', Icon: Keyboard, tags: ['type', 'input', 'device'] },
  { name: 'HardDrive', Icon: HardDrive, tags: ['storage', 'disk'] },
  { name: 'Disc', Icon: Disc, tags: ['cd', 'dvd', 'media'] },
  { name: 'Disc3', Icon: Disc3, tags: ['album', 'record', 'music'] },
  { name: 'Album', Icon: Album, tags: ['music', 'record', 'collection'] },
  { name: 'MemoryStick', Icon: MemoryStick, tags: ['ram', 'storage'] },
  { name: 'Joystick', Icon: Joystick, tags: ['game', 'play', 'controller'] },

  // ─── Home & chores ───────────────────────────────
  { name: 'WashingMachine', Icon: WashingMachine, tags: ['laundry', 'clean', 'chore'] },
  { name: 'Sofa', Icon: Sofa, tags: ['couch', 'living-room', 'rest'] },
  { name: 'Bath', Icon: Bath, tags: ['shower', 'bathroom', 'clean'] },
  { name: 'Toilet', Icon: Toilet, tags: ['bathroom', 'restroom'] },
  { name: 'ShowerHead', Icon: ShowerHead, tags: ['bath', 'morning', 'clean'] },
  { name: 'BedDouble', Icon: BedDouble, tags: ['sleep', 'bedroom'] },
  { name: 'BedSingle', Icon: BedSingle, tags: ['sleep', 'bedroom'] },
  { name: 'Armchair', Icon: Armchair, tags: ['relax', 'living-room', 'chair'] },
  { name: 'Microwave', Icon: Microwave, tags: ['kitchen', 'cook', 'heat'] },
  { name: 'LampCeiling', Icon: LampCeiling, tags: ['light', 'home'] },
  { name: 'LampDesk', Icon: LampDesk, tags: ['light', 'work'] },
  { name: 'LampFloor', Icon: LampFloor, tags: ['light', 'home'] },
  { name: 'DoorOpen', Icon: DoorOpen, tags: ['enter', 'leave', 'door'] },
  { name: 'DoorClosed', Icon: DoorClosed, tags: ['locked', 'closed', 'private'] },
  { name: 'Vault', Icon: Vault, tags: ['safe', 'secure', 'storage'] },

  // ─── Tools & construction ────────────────────────
  { name: 'Drill', Icon: Drill, tags: ['tool', 'build', 'fix'] },
  { name: 'Pickaxe', Icon: Pickaxe, tags: ['mine', 'dig', 'tool'] },
  { name: 'Axe', Icon: Axe, tags: ['chop', 'tool', 'wood'] },
  { name: 'Cog', Icon: Cog, tags: ['settings', 'gear', 'config'] },
  { name: 'Settings2', Icon: Settings2, tags: ['preferences', 'config', 'sliders'] },
  { name: 'HardHat', Icon: HardHat, tags: ['construction', 'safety', 'work'] },
  { name: 'Construction', Icon: Construction, tags: ['build', 'wip', 'work-in-progress'] },
  { name: 'Magnet', Icon: Magnet, tags: ['attract', 'pull', 'physics'] },

  // ─── School & education ──────────────────────────
  { name: 'School', Icon: School, tags: ['education', 'class', 'learn'] },
  { name: 'BookA', Icon: BookA, tags: ['dictionary', 'study', 'read'] },
  { name: 'BookCheck', Icon: BookCheck, tags: ['done', 'study', 'read'] },
  { name: 'BookHeart', Icon: BookHeart, tags: ['favorite', 'read'] },
  { name: 'BookMarked', Icon: BookMarked, tags: ['saved', 'read'] },
  { name: 'BookText', Icon: BookText, tags: ['read', 'study'] },
  { name: 'BookKey', Icon: BookKey, tags: ['secret', 'guide'] },
  { name: 'BookPlus', Icon: BookPlus, tags: ['add', 'new', 'read'] },
  { name: 'BookMinus', Icon: BookMinus, tags: ['remove', 'read'] },
  { name: 'BookX', Icon: BookX, tags: ['delete', 'read'] },
  { name: 'NotebookPen', Icon: NotebookPen, tags: ['write', 'journal', 'notes'] },
  { name: 'NotebookText', Icon: NotebookText, tags: ['journal', 'notes'] },
  { name: 'NotebookTabs', Icon: NotebookTabs, tags: ['organize', 'notes'] },
  { name: 'Pencil', Icon: Pencil, tags: ['write', 'draw', 'edit'] },
  { name: 'PencilRuler', Icon: PencilRuler, tags: ['design', 'draft', 'measure'] },
  { name: 'Highlighter', Icon: Highlighter, tags: ['mark', 'study', 'emphasize'] },
  { name: 'Eraser', Icon: Eraser, tags: ['delete', 'undo', 'remove'] },
  { name: 'Atom', Icon: Atom, tags: ['science', 'physics', 'chem'] },
  { name: 'Telescope', Icon: Telescope, tags: ['astronomy', 'observe', 'space'] },
  { name: 'Microscope', Icon: Microscope, tags: ['science', 'biology', 'lab'] },
  { name: 'TestTube', Icon: TestTube, tags: ['lab', 'science', 'chem'] },
  { name: 'TestTubes', Icon: TestTubes, tags: ['lab', 'science', 'experiment'] },
  { name: 'Binoculars', Icon: Binoculars, tags: ['look', 'observe', 'spot'] },
  { name: 'Sigma', Icon: Sigma, tags: ['math', 'sum', 'stats'] },
  { name: 'Infinity', Icon: Infinity, tags: ['math', 'forever', 'loop'] },
  { name: 'Variable', Icon: Variable, tags: ['math', 'algebra'] },

  // ─── Sports & fitness ────────────────────────────
  { name: 'Medal', Icon: Medal, tags: ['win', 'achievement', 'sport'] },
  { name: 'Volleyball', Icon: Volleyball, tags: ['sport', 'play', 'beach'] },
  { name: 'Goal', Icon: Goal, tags: ['target', 'achievement'] },
  { name: 'MountainSnow', Icon: MountainSnow, tags: ['ski', 'winter', 'outdoor'] },

  // ─── Arts & creative ─────────────────────────────
  { name: 'Drum', Icon: Drum, tags: ['music', 'percussion', 'practice'] },
  { name: 'Piano', Icon: Piano, tags: ['music', 'keys', 'practice'] },
  { name: 'Music2', Icon: Music2, tags: ['song', 'audio'] },
  { name: 'Music3', Icon: Music3, tags: ['song', 'audio'] },
  { name: 'Music4', Icon: Music4, tags: ['song', 'audio'] },
  { name: 'Mic2', Icon: Mic2, tags: ['record', 'voice', 'singer'] },
  { name: 'Speaker', Icon: Speaker, tags: ['audio', 'sound', 'play'] },
  { name: 'Drama', Icon: Drama, tags: ['theater', 'masks', 'acting'] },
  { name: 'Theater', Icon: Theater, tags: ['show', 'performance', 'stage'] },
  { name: 'Ribbon', Icon: Ribbon, tags: ['award', 'gift', 'cause'] },
  { name: 'Diamond', Icon: Diamond, tags: ['premium', 'gem', 'value'] },
  { name: 'Gem', Icon: Gem, tags: ['premium', 'rare', 'value'] },
  { name: 'Gift', Icon: Gift, tags: ['present', 'birthday', 'celebrate'] },

  // ─── Time & schedule ─────────────────────────────
  { name: 'Clock', Icon: Clock, tags: ['time', 'hour'] },
  { name: 'Hourglass', Icon: Hourglass, tags: ['wait', 'time', 'patience'] },
  { name: 'History', Icon: History, tags: ['past', 'log', 'undo'] },
  { name: 'CalendarCheck', Icon: CalendarCheck, tags: ['done', 'scheduled', 'event'] },
  { name: 'CalendarClock', Icon: CalendarClock, tags: ['schedule', 'date', 'time'] },
  { name: 'CalendarDays', Icon: CalendarDays, tags: ['month', 'view', 'schedule'] },
  { name: 'CalendarHeart', Icon: CalendarHeart, tags: ['anniversary', 'date', 'special'] },
  { name: 'CalendarMinus', Icon: CalendarMinus, tags: ['cancel', 'remove-event'] },
  { name: 'CalendarPlus', Icon: CalendarPlus, tags: ['add-event', 'schedule'] },
  { name: 'CalendarRange', Icon: CalendarRange, tags: ['span', 'period'] },
  { name: 'CalendarSearch', Icon: CalendarSearch, tags: ['find-date', 'lookup'] },
  { name: 'CalendarX', Icon: CalendarX, tags: ['cancel', 'unavailable'] },
  { name: 'AlarmClockCheck', Icon: AlarmClockCheck, tags: ['set', 'alarm-done'] },
  { name: 'AlarmClockOff', Icon: AlarmClockOff, tags: ['disable', 'no-alarm'] },
  { name: 'AlarmClockPlus', Icon: AlarmClockPlus, tags: ['add-alarm'] },

  // ─── States & feedback ───────────────────────────
  { name: 'AlertCircle', Icon: AlertCircle, tags: ['warning', 'issue', 'attention'] },
  { name: 'AlertTriangle', Icon: AlertTriangle, tags: ['warning', 'danger', 'caution'] },
  { name: 'AlertOctagon', Icon: AlertOctagon, tags: ['stop', 'critical', 'danger'] },
  { name: 'Info', Icon: Info, tags: ['detail', 'help', 'about'] },
  { name: 'HelpCircle', Icon: HelpCircle, tags: ['question', 'support', 'faq'] },
  { name: 'Square', Icon: Square, tags: ['shape', 'empty', 'box'] },

  // ─── Direction & motion ──────────────────────────
  { name: 'ArrowUp', Icon: ArrowUp, tags: ['up', 'rise'] },
  { name: 'ArrowDown', Icon: ArrowDown, tags: ['down', 'fall'] },
  { name: 'ArrowLeft', Icon: ArrowLeft, tags: ['back', 'previous'] },
  { name: 'ArrowRight', Icon: ArrowRight, tags: ['next', 'forward'] },
  { name: 'ArrowUpRight', Icon: ArrowUpRight, tags: ['external', 'open'] },
  { name: 'ArrowDownRight', Icon: ArrowDownRight, tags: ['external', 'down-right'] },
  { name: 'ArrowUpLeft', Icon: ArrowUpLeft, tags: ['back', 'up-left'] },
  { name: 'ArrowDownLeft', Icon: ArrowDownLeft, tags: ['back', 'down-left'] },
  { name: 'ChevronUp', Icon: ChevronUp, tags: ['expand', 'up'] },
  { name: 'ChevronDown', Icon: ChevronDown, tags: ['expand', 'down', 'more'] },
  { name: 'ChevronLeft', Icon: ChevronLeft, tags: ['back', 'prev'] },
  { name: 'ChevronRight', Icon: ChevronRight, tags: ['next', 'forward'] },
  { name: 'CornerUpLeft', Icon: CornerUpLeft, tags: ['back', 'undo'] },
  { name: 'CornerUpRight', Icon: CornerUpRight, tags: ['redo', 'forward'] },
  { name: 'Move', Icon: Move, tags: ['drag', 'reposition'] },
  { name: 'MoveHorizontal', Icon: MoveHorizontal, tags: ['resize', 'horizontal'] },
  { name: 'MoveVertical', Icon: MoveVertical, tags: ['resize', 'vertical'] },
  { name: 'RotateCw', Icon: RotateCw, tags: ['rotate', 'redo'] },
  { name: 'RotateCcw', Icon: RotateCcw, tags: ['rotate', 'undo'] },
  { name: 'RefreshCw', Icon: RefreshCw, tags: ['reload', 'sync'] },
  { name: 'RefreshCcw', Icon: RefreshCcw, tags: ['reload', 'undo'] },
  { name: 'FlipHorizontal', Icon: FlipHorizontal, tags: ['mirror', 'flip'] },
  { name: 'FlipVertical', Icon: FlipVertical, tags: ['mirror', 'flip'] },
  { name: 'Undo', Icon: Undo, tags: ['back', 'revert'] },
  { name: 'Save', Icon: Save, tags: ['store', 'disk', 'submit'] },
  { name: 'Upload', Icon: Upload, tags: ['send', 'import'] },

  // ─── Security & privacy ──────────────────────────
  { name: 'Lock', Icon: Lock, tags: ['secure', 'private', 'locked'] },
  { name: 'Unlock', Icon: Unlock, tags: ['open', 'access'] },
  { name: 'LockKeyhole', Icon: LockKeyhole, tags: ['secure', 'private'] },
  { name: 'KeyRound', Icon: KeyRound, tags: ['auth', 'unlock'] },
  { name: 'KeySquare', Icon: KeySquare, tags: ['auth', 'unlock'] },
  { name: 'Fingerprint', Icon: Fingerprint, tags: ['biometric', 'auth', 'identity'] },
  { name: 'ScanFace', Icon: ScanFace, tags: ['face-id', 'auth', 'identity'] },
  { name: 'ShieldCheck', Icon: ShieldCheck, tags: ['verified', 'secure', 'safe'] },
  { name: 'ShieldAlert', Icon: ShieldAlert, tags: ['warning', 'security'] },
  { name: 'ShieldX', Icon: ShieldX, tags: ['unprotected', 'unsafe'] },
  { name: 'ShieldOff', Icon: ShieldOff, tags: ['disabled', 'unprotected'] },

  // ─── Misc useful ─────────────────────────────────
  { name: 'Tag', Icon: Tag, tags: ['label', 'category', 'price'] },
  { name: 'Tags', Icon: Tags, tags: ['labels', 'categories'] },
  { name: 'BookmarkCheck', Icon: BookmarkCheck, tags: ['saved', 'done'] },
  { name: 'BookmarkPlus', Icon: BookmarkPlus, tags: ['add', 'save'] },
  { name: 'BookmarkMinus', Icon: BookmarkMinus, tags: ['remove'] },
  { name: 'BookmarkX', Icon: BookmarkX, tags: ['delete'] },
  { name: 'Sticker', Icon: Sticker, tags: ['fun', 'label', 'decorate'] },
  { name: 'StickyNote', Icon: StickyNote, tags: ['memo', 'reminder', 'note'] },
  { name: 'Paperclip', Icon: Paperclip, tags: ['attach', 'file', 'clip'] },
  { name: 'Crosshair', Icon: Crosshair, tags: ['target', 'aim', 'focus'] },
  { name: 'Focus', Icon: Focus, tags: ['target', 'aim', 'sharp'] },
  { name: 'Pen', Icon: Pen, tags: ['write', 'edit'] },
  { name: 'Building2Alt', Icon: Building, tags: ['office', 'tower'] },
];

const BY_NAME = new Map<string, IconEntry>(ENTRIES.map(e => [e.name, e]));

export const ICON_LIBRARY: ReadonlyArray<IconEntry> = ENTRIES;

/** Lookup an icon component by stored name. Returns null when not found. */
export function getIconByName(name: string | null | undefined): LucideIcon | null {
  if (!name) return null;
  return BY_NAME.get(name)?.Icon ?? null;
}

/** Free-text search across name + tags. Returns matching entries, max `limit`. */
export function searchIcons(query: string, limit = 200): IconEntry[] {
  const q = query.trim().toLowerCase();
  if (!q) return ENTRIES.slice(0, limit);
  const out: IconEntry[] = [];
  for (const e of ENTRIES) {
    const haystack = `${e.name.toLowerCase()} ${e.tags.join(' ')}`;
    if (haystack.includes(q)) out.push(e);
    if (out.length >= limit) break;
  }
  return out;
}

/**
 * Suggest icons that fit the given freeform text (task title, tag label, etc.).
 * Returns up to `limit` entries ranked by token-overlap with names + tags.
 */
export function suggestIcons(text: string, limit = 6): IconEntry[] {
  const tokens = text
    .toLowerCase()
    .split(/[^a-z0-9]+/)
    .filter(t => t.length >= 3);
  if (tokens.length === 0) return [];

  const scored: { entry: IconEntry; score: number }[] = [];
  for (const entry of ENTRIES) {
    const nameLower = entry.name.toLowerCase();
    let score = 0;
    for (const tok of tokens) {
      // Exact tag match is strongest
      if (entry.tags.includes(tok)) score += 5;
      // Substring match in any tag
      else if (entry.tags.some(tag => tag.includes(tok) || tok.includes(tag))) score += 3;
      // Name match
      if (nameLower === tok) score += 4;
      else if (nameLower.includes(tok)) score += 2;
    }
    if (score > 0) scored.push({ entry, score });
  }
  scored.sort((a, b) => b.score - a.score);
  return scored.slice(0, limit).map(s => s.entry);
}
