import {
  Accessibility, Activity, Airplay, AlarmClock, AlarmClockCheck, AlarmClockOff, AlarmClockPlus,
  AlertCircle, AlertOctagon, AlertTriangle, Album, Ambulance, Anchor, Angry, Annoyed, Apple,
  Archive, Armchair, ArrowDown, ArrowDownLeft, ArrowDownRight, ArrowLeft, ArrowRight, ArrowUp,
  ArrowUpLeft, ArrowUpRight, AtSign, Atom, Award, Axe, Baby, Backpack, BadgePercent, Banana,
  Bandage, Banknote, BarChart3, Bath, Battery, BatteryCharging, BatteryFull, BatteryLow,
  BatteryMedium, BatteryWarning, Beaker, Bed, BedDouble, BedSingle, Beef, Beer, BeerOff, Bell,
  BellDot, BellMinus, BellOff, BellPlus, BellRing, Bike, Binoculars, Bird, Bitcoin, Bluetooth,
  BluetoothOff, Bone, BookA, BookCheck, BookHeart, BookKey, BookMarked, BookMinus, BookOpen,
  BookPlus, BookText, BookX, Bookmark, BookmarkCheck, BookmarkMinus, BookmarkPlus, BookmarkX,
  Boxes, Brain, Briefcase, Brush, Bug, Building, Building2, Bus, Cable, Cake, Calculator,
  Calendar, CalendarCheck, CalendarClock, CalendarDays, CalendarHeart, CalendarMinus,
  CalendarPlus, CalendarRange, CalendarSearch, CalendarX, Camera, Candy, CandyCane, Car,
  Caravan, Carrot, Cast, Cat, ChartArea, ChartBar, ChartCandlestick,
  ChartColumn, ChartLine, ChartPie, ChefHat, Cherry, ChevronDown, ChevronLeft, ChevronRight,
  ChevronUp, Cigarette, Citrus, Clapperboard, ClipboardCheck, ClipboardList, Clock, Clover,
  Cloud, CloudDownload, CloudDrizzle, CloudFog, CloudHail, CloudLightning, CloudMoon, CloudOff,
  CloudRain, CloudRainWind, CloudSnow, CloudSun, CloudUpload, Code2, Codepen, Coffee, Cog,
  Coins, Compass, Construction, Contact, Cookie, CookingPot, CornerUpLeft, CornerUpRight, Cpu,
  CreditCard, Croissant, Cross, Crosshair, Crown, CupSoda, Database, Diamond, Disc, Disc3, Dna,
  Dog, Donut, DoorClosed, DoorOpen, Drama, Drill, Droplet, Droplets, Drum, Drumstick, Dumbbell,
  Ear, EarOff, Eclipse, Egg, Eraser, Euro, Eye, EyeOff, Feather, File, FileAudio, FileCheck,
  FileCode, FileHeart, FileImage, FileLock, FileMinus, FilePen, FilePlus, FileSearch,
  FileSpreadsheet, FileText, FileVideo, FileWarning, FileX, Files, Film, Fingerprint,
  Fish, Flag, Flame, FlaskConical, FlipHorizontal, FlipVertical, Flower, Flower2,
  Focus, Folder, FolderArchive, FolderHeart, FolderLock, FolderOpen, FolderPlus, FolderSearch,
  FolderTree, Footprints, Forward, Frown, Fuel, Gamepad2, Gauge, Gem, Gift, GitBranch,
  GitCommitHorizontal, GitFork, GitMerge, GitPullRequest, Github, Gitlab, GlassWater, Glasses,
  Globe, Globe2, Goal, GraduationCap, Grape, Guitar, Ham, Hammer, Hand, HandCoins, HandHeart,
  HandHelping, HandMetal, HandPlatter, Handshake, HardDrive, HardHat, Hash, Haze, Headphones,
  Heart, HeartHandshake, HeartPulse, HelpCircle, Highlighter, History, Home, Hospital,
  Hourglass, IceCream, Image, IndianRupee, Inbox, Infinity, Info, JapaneseYen, Joystick,
  Key, KeyRound, KeySquare, Keyboard, Lamp, LampCeiling, LampDesk, LampFloor, Landmark,
  Languages, Laptop, Laugh, Leaf, LeafyGreen, Library, Lightbulb, Link, ListChecks, ListFilter,
  ListMinus, ListOrdered, ListPlus, ListTodo, ListX, Lock, LockKeyhole, Lollipop, Luggage,
  Magnet, Mail, Map as MapIcon, MapPin, MapPinned, Martini, Medal, Meh, MemoryStick, MessageCircle,
  MessageCircleHeart, MessageCircleMore, MessageCircleQuestion, MessageSquare, MessagesSquare,
  Mic, Mic2, Microscope, Microwave, Milestone, Milk, MilkOff, Monitor, Moon, Mountain,
  MountainSnow, Mouse, MousePointer, Move, MoveHorizontal, MoveVertical, Music, Music2,
  Music3, Music4, Navigation, NavigationOff, Network, Newspaper, Notebook, NotebookPen,
  NotebookTabs, NotebookText, Orbit, Package, Palette, Paperclip, ParkingCircle,
  ParkingSquare, PartyPopper, PawPrint, Pen, PenLine, PenTool, Pencil, PencilRuler, Percent,
  PersonStanding, Phone, PhoneCall, PhoneIncoming, PhoneOff, PhoneOutgoing, Piano, Pickaxe,
  PiggyBank, Pill, Pin, Pizza, Plane, Plug, Pointer, Popcorn, Power, PowerOff, Printer,
  Puzzle, Rabbit, Radio, Rainbow, Rat, Receipt, Recycle, RefreshCcw, RefreshCw, Reply,
  Ribbon, Rocket, RotateCcw, RotateCw, Route, Rss, Ruler, Sailboat, Salad, Sandwich, Save,
  Scale, ScanFace, School, Scissors, ScreenShare, ScrollText, Search, Send,
  SendHorizontal, Server, ServerOff, Settings, Settings2, Share2, Shield, ShieldAlert,
  ShieldCheck, ShieldOff, ShieldX, Ship, ShoppingBag, ShoppingBasket, ShoppingCart, ShowerHead,
  Shovel, Shrub, Sigma, Skull, Slack, Smartphone, Smile, Snail, Snowflake, Sofa, Soup, Speaker,
  Sparkles, Sprout, Square, Star, Sticker, StickyNote, Stethoscope, Sun, Sunrise, Sunset,
  Syringe, Tablet, Tag, Tags, Target, Telescope, Tent, Terminal, TestTube, TestTubes,
  Theater, Thermometer, ThermometerSnowflake, ThermometerSun, Ticket, Timer, Toilet, Tornado,
  Train, TramFront, TreeDeciduous, TreePalm, TreePine, TrendingDown, TrendingUp, Trophy,
  Truck, Turtle, Tv, Umbrella, Undo, Unlock, Upload, Usb, User, UserCheck, UserCog, UserMinus,
  UserPlus, UserRoundX, UserX, Users, Utensils, Variable, Vault, Vegan, Video, Voicemail,
  Volleyball, Volume, Volume1, Volume2, VolumeX, Wallet, Wand2, WashingMachine, Watch, Waves,
  Wheat, WheatOff, Wifi, WifiOff, Wind, Wine, WineOff, Workflow, Worm, Wrench, X, Zap,
  DollarSign, Megaphone,
  AArrowDown, AArrowUp, ALargeSmall, ActivitySquare, AirVent, AlarmCheck, AlarmClockMinus,
  AlarmSmoke, AlignCenter, AlignCenterHorizontal, AlignCenterVertical, AlignEndHorizontal,
  AlignEndVertical, AlignHorizontalDistributeCenter, AlignHorizontalDistributeEnd,
  AlignHorizontalDistributeStart, AlignHorizontalJustifyCenter, AlignHorizontalJustifyEnd,
  AlignHorizontalJustifyStart, AlignHorizontalSpaceAround, AlignHorizontalSpaceBetween,
  AlignJustify, AlignLeft, AlignRight, AlignStartHorizontal, AlignStartVertical,
  AlignVerticalDistributeCenter, AlignVerticalDistributeEnd, AlignVerticalDistributeStart,
  AlignVerticalJustifyCenter, AlignVerticalJustifyEnd, AlignVerticalJustifyStart,
  AlignVerticalSpaceAround, AlignVerticalSpaceBetween, Ampersand, Ampersands, Amphora, Antenna,
  Anvil, Aperture, AppWindow, AppWindowMac, ArchiveRestore, ArchiveX, AreaChart, ArrowBigDown,
  ArrowBigDownDash, ArrowBigLeft, ArrowBigLeftDash, ArrowBigRight, ArrowBigRightDash, ArrowBigUp,
  ArrowBigUpDash, ArrowDown01, ArrowDown10, ArrowDownAZ, ArrowDownCircle, ArrowDownFromLine,
  ArrowDownLeftFromCircle, ArrowDownLeftFromSquare, ArrowDownLeftSquare, ArrowDownNarrowWide,
  ArrowDownRightFromCircle, ArrowDownRightFromSquare, ArrowDownRightSquare, ArrowDownSquare,
  ArrowDownToDot, ArrowDownToLine, ArrowDownUp, ArrowDownWideNarrow, ArrowDownZA, ArrowLeftCircle,
  ArrowLeftFromLine, ArrowLeftRight, ArrowLeftSquare, ArrowLeftToLine, ArrowRightCircle,
  ArrowRightFromLine, ArrowRightLeft, ArrowRightSquare, ArrowRightToLine, ArrowUp01, ArrowUp10,
  ArrowUpAZ, ArrowUpCircle, ArrowUpDown, ArrowUpFromDot, ArrowUpFromLine, ArrowUpLeftFromCircle,
  ArrowUpLeftFromSquare, ArrowUpLeftSquare, ArrowUpNarrowWide, ArrowUpRightFromCircle,
  ArrowUpRightFromSquare, ArrowUpRightSquare, ArrowUpSquare, ArrowUpToLine, ArrowUpWideNarrow,
  ArrowUpZA, ArrowsUpFromLine, Asterisk, AsteriskSquare, AudioLines, AudioWaveform, Axis3D, Badge,
  BadgeAlert, BadgeCent, BadgeCheck, BadgeDollarSign, BadgeEuro, BadgeHelp, BadgeIndianRupee,
  BadgeInfo, BadgeJapaneseYen, BadgeMinus, BadgePlus, BadgePoundSterling, BadgeRussianRuble,
  BadgeSwissFranc, BadgeX, BaggageClaim, Ban, BarChart2, BarChart4, BarChartBig,
  BarChartHorizontal, BarChartHorizontalBig, Barcode, Baseline, Bean, BeanOff, BellElectric,
  BetweenHorizonalEnd, BetweenHorizonalStart, BetweenVerticalEnd, BetweenVerticalStart,
  BicepsFlexed, Binary, Biohazard, Blend, Blinds, Blocks, BluetoothConnected, BluetoothSearching,
  Bold, Bolt, Bomb, Book, BookAudio, BookCopy, BookDashed, BookDown, BookHeadphones, BookImage,
  BookLock, BookOpenCheck, BookOpenText, BookType, BookUp, BookUp2, BookUser, BoomBox, Bot,
  BotMessageSquare, BotOff, Box, BoxSelect, Braces, Brackets, BrainCircuit, BrainCog, BrickWall,
  BriefcaseBusiness, BriefcaseConveyorBelt, BriefcaseMedical, BringToFront, BugOff, BugPlay,
  BusFront, CableCar, CakeSlice, Calendar1, CalendarArrowDown, CalendarArrowUp, CalendarCheck2,
  CalendarCog, CalendarFold, CalendarMinus2, CalendarOff, CalendarPlus2, CalendarSync, CalendarX2,
  CameraOff, CandlestickChart, CandyOff, Cannabis, Captions, CaptionsOff, CarFront, CarTaxiFront,
  CaseLower, CaseSensitive, CaseUpper, CassetteTape, Castle, Cctv, ChartBarDecreasing,
  ChartBarIncreasing, ChartBarStacked, ChartColumnDecreasing, ChartColumnStacked, ChartGantt,
  ChartNetwork, ChartNoAxesColumnDecreasing, ChartNoAxesCombined, ChartNoAxesGantt, ChartScatter,
  ChartSpline, Check, CheckCheck, CheckCircle, CheckCircle2, CheckSquare, CheckSquare2,
  ChevronDownCircle, ChevronDownSquare, ChevronFirst, ChevronLast, ChevronLeftCircle,
  ChevronLeftSquare, ChevronRightCircle, ChevronRightSquare, ChevronUpCircle, ChevronUpSquare,
  ChevronsDown, ChevronsDownUp, ChevronsLeft, ChevronsLeftRight, ChevronsLeftRightEllipsis,
  ChevronsRight, ChevronsRightLeft, ChevronsUp, ChevronsUpDown, Chrome, Church, CigaretteOff,
  Circle, CircleDashed, CircleDivide, CircleDollarSign, CircleDot, CircleDotDashed,
  CircleEllipsis, CircleEqual, CircleFadingArrowUp, CircleFadingPlus, CircleGauge, CircleHelp,
  CircleMinus, CircleOff, CircleParking, CircleParkingOff, CirclePause, CirclePercent, CirclePlay,
  CirclePlus, CirclePower, CircleSlash, CircleSlash2, CircleStop, CircleUser, CircleUserRound,
  CircleX, CircuitBoard, ClipboardCopy, ClipboardEdit, ClipboardMinus, ClipboardPaste,
  ClipboardPenLine, ClipboardPlus, ClipboardType, ClipboardX, Clock1, Clock10, Clock11, Clock12,
  Clock2, Clock3, Clock4, Clock5, Clock6, Clock7, Clock8, Clock9, ClockAlert, ClockArrowDown,
  ClockArrowUp, CloudAlert, CloudCog, CloudMoonRain, CloudSunRain, Cloudy, Club, CodeSquare,
  Codesandbox, Columns, Columns3, Columns4, Combine, Command, Component, Computer, ConciergeBell,
  Cone, Contact2, Container, Contrast, Copy, CopyCheck, CopyMinus, CopyPlus, CopySlash, CopyX,
  Copyleft, Copyright, CornerDownLeft, CornerDownRight, CornerLeftDown, CornerLeftUp,
  CornerRightDown, CornerRightUp, CreativeCommons, Crop, Cuboid, Currency, Cylinder, Dam,
  DatabaseBackup, DatabaseZap, Delete, Dessert, Diameter, DiamondMinus, DiamondPercent,
  DiamondPlus, Dice1, Dice2, Dice3, Dice4, Dice5, Dice6, Dices, Diff, Disc2, DiscAlbum, Divide,
  DivideSquare, DnaOff, Dock, Dot, DotSquare, Download, DraftingCompass, Dribbble, Earth,
  EarthLock, Edit, Edit2, Edit3, EggFried, EggOff, Ellipsis, EllipsisVertical, Equal,
  EqualApproximately, EqualNot, EqualSquare, EthernetPort, Expand, ExternalLink, EyeClosed,
  Facebook, Factory, Fan, FastForward, Fence, FerrisWheel, Figma, FileArchive, FileAudio2,
  FileAxis3D, FileBadge, FileBadge2, FileBarChart, FileBarChart2, FileBox, FileChartLine,
  FileChartPie, FileCheck2, FileClock, FileCode2, FileCog, FileDiff, FileDigit, FileDown,
  FileEdit, FileInput, FileJson, FileJson2, FileKey, FileKey2, FileLock2, FileMinus2, FileMusic,
  FileOutput, FilePenLine, FilePlus2, FileQuestion, FileScan, FileSearch2, FileSliders, FileStack,
  FileSymlink, FileTerminal, FileType, FileType2, FileUp, FileUser, FileVideo2, FileVolume,
  FileVolume2, FileX2, Filter, FilterX, FireExtinguisher, FishOff, FishSymbol, FlagOff,
  FlagTriangleLeft, FlagTriangleRight, FlameKindling, Flashlight, FlashlightOff, FlaskConicalOff,
  FlaskRound, FlipHorizontal2, FlipVertical2, FoldHorizontal, FoldVertical, FolderCheck,
  FolderClock, FolderClosed, FolderCode, FolderCog, FolderDot, FolderDown, FolderEdit, FolderGit,
  FolderGit2, FolderInput, FolderKanban, FolderKey, FolderMinus, FolderOpenDot, FolderOutput,
  FolderRoot, FolderSearch2, FolderSymlink, FolderSync, FolderUp, FolderX, Folders, ForkKnife,
  ForkKnifeCrossed, Forklift, FormInput, Frame, Framer, Fullscreen, FunctionSquare,
  GalleryHorizontal, GalleryHorizontalEnd,
  type LucideIcon,
} from 'lucide-react';

interface IconEntry {
  name: string;
  Icon: LucideIcon;
  /** Lowercase keywords used by search + suggestions. Name itself is always included. */
  tags: string[];
}

/** Curated whitelist. Order matters for tie-breaking in suggestions. */
const ENTRIES: IconEntry[] = [
  { name: 'Activity', Icon: Activity, tags: ['pulse', 'health', 'heart', 'fitness'] },
  { name: 'AlarmClock', Icon: AlarmClock, tags: ['alarm', 'wake', 'time'] },
  { name: 'Apple', Icon: Apple, tags: ['fruit', 'food', 'snack'] },
  { name: 'Archive', Icon: Archive, tags: ['box', 'storage'] },
  { name: 'Award', Icon: Award, tags: ['medal', 'prize', 'win'] },
  { name: 'Baby', Icon: Baby, tags: ['child', 'kid', 'parent', 'family'] },
  { name: 'Banknote', Icon: Banknote, tags: ['money', 'cash', 'finance'] },
  { name: 'BarChart', Icon: BarChart3, tags: ['analytics', 'stats', 'metrics', 'chart'] },
  { name: 'Beaker', Icon: Beaker, tags: ['lab', 'science', 'experiment'] },
  { name: 'Bed', Icon: Bed, tags: ['sleep', 'rest', 'nap'] },
  { name: 'Bell', Icon: Bell, tags: ['alert', 'notification', 'reminder'] },
  { name: 'Bike', Icon: Bike, tags: ['cycle', 'ride', 'commute', 'sport'] },
  { name: 'BookOpen', Icon: BookOpen, tags: ['read', 'book', 'study', 'learn'] },
  { name: 'Bookmark', Icon: Bookmark, tags: ['save', 'mark'] },
  { name: 'Briefcase', Icon: Briefcase, tags: ['work', 'job', 'office', 'business'] },
  { name: 'Brush', Icon: Brush, tags: ['paint', 'art', 'design', 'draw'] },
  { name: 'Bug', Icon: Bug, tags: ['debug', 'issue', 'fix'] },
  { name: 'Building', Icon: Building2, tags: ['office', 'company', 'corporate'] },
  { name: 'Cake', Icon: Cake, tags: ['birthday', 'dessert', 'celebrate'] },
  { name: 'Calculator', Icon: Calculator, tags: ['math', 'finance', 'numbers'] },
  { name: 'Calendar', Icon: Calendar, tags: ['date', 'schedule', 'event'] },
  { name: 'Camera', Icon: Camera, tags: ['photo', 'picture', 'shoot'] },
  { name: 'Car', Icon: Car, tags: ['drive', 'vehicle', 'commute'] },
  { name: 'Carrot', Icon: Carrot, tags: ['veggie', 'food', 'cook'] },
  { name: 'ChartLine', Icon: ChartLine, tags: ['growth', 'trend', 'metric'] },
  { name: 'Cherry', Icon: Cherry, tags: ['fruit', 'snack'] },
  { name: 'ChefHat', Icon: ChefHat, tags: ['cook', 'kitchen', 'food', 'recipe'] },
  { name: 'Cigarette', Icon: Cigarette, tags: ['smoke', 'break'] },
  { name: 'Clapperboard', Icon: Clapperboard, tags: ['film', 'movie', 'video', 'shoot'] },
  { name: 'Clipboard', Icon: ClipboardList, tags: ['list', 'todo', 'task', 'checklist'] },
  { name: 'Cloud', Icon: Cloud, tags: ['weather', 'sync', 'storage'] },
  { name: 'Code', Icon: Code2, tags: ['dev', 'program', 'engineering', 'ship'] },
  { name: 'Coffee', Icon: Coffee, tags: ['drink', 'break', 'cafe', 'morning'] },
  { name: 'Compass', Icon: Compass, tags: ['navigate', 'direction', 'explore'] },
  { name: 'Cpu', Icon: Cpu, tags: ['computer', 'hardware', 'tech'] },
  { name: 'CreditCard', Icon: CreditCard, tags: ['pay', 'finance', 'card', 'bill'] },
  { name: 'Croissant', Icon: Croissant, tags: ['bakery', 'breakfast', 'food'] },
  { name: 'Crown', Icon: Crown, tags: ['premium', 'royal', 'priority'] },
  { name: 'Database', Icon: Database, tags: ['data', 'storage', 'sql'] },
  { name: 'Dollar', Icon: DollarSign, tags: ['money', 'finance', 'pay'] },
  { name: 'Dog', Icon: Dog, tags: ['pet', 'walk', 'animal'] },
  { name: 'Dumbbell', Icon: Dumbbell, tags: ['gym', 'workout', 'lift', 'fitness', 'strength'] },
  { name: 'Egg', Icon: Egg, tags: ['breakfast', 'cook', 'food'] },
  { name: 'Feather', Icon: Feather, tags: ['light', 'write', 'quill'] },
  { name: 'Film', Icon: Film, tags: ['movie', 'video', 'cinema', 'edit'] },
  { name: 'Flag', Icon: Flag, tags: ['goal', 'milestone', 'finish'] },
  { name: 'Flame', Icon: Flame, tags: ['streak', 'hot', 'fire', 'energy'] },
  { name: 'Flask', Icon: FlaskConical, tags: ['lab', 'science', 'chem'] },
  { name: 'Flower', Icon: Flower2, tags: ['garden', 'plant', 'nature'] },
  { name: 'Folder', Icon: Folder, tags: ['file', 'organize', 'project'] },
  { name: 'Footprints', Icon: Footprints, tags: ['walk', 'stroll', 'step', 'hike'] },
  { name: 'Gamepad', Icon: Gamepad2, tags: ['game', 'play', 'console'] },
  { name: 'Gauge', Icon: Gauge, tags: ['speed', 'meter', 'measure'] },
  { name: 'Graduation', Icon: GraduationCap, tags: ['school', 'study', 'learn', 'edu'] },
  { name: 'Guitar', Icon: Guitar, tags: ['music', 'practice', 'instrument'] },
  { name: 'Hammer', Icon: Hammer, tags: ['build', 'fix', 'tool', 'repair'] },
  { name: 'Hand', Icon: Hand, tags: ['wave', 'hello', 'stop'] },
  { name: 'Headphones', Icon: Headphones, tags: ['music', 'listen', 'audio', 'podcast'] },
  { name: 'Heart', Icon: Heart, tags: ['love', 'favorite', 'like'] },
  { name: 'HeartHandshake', Icon: HeartHandshake, tags: ['wedding', 'engage', 'anniversary', 'love', 'date'] },
  { name: 'Home', Icon: Home, tags: ['house', 'clean', 'laundry', 'chore'] },
  { name: 'IceCream', Icon: IceCream, tags: ['dessert', 'sweet', 'snack'] },
  { name: 'Image', Icon: Image, tags: ['photo', 'picture'] },
  { name: 'Inbox', Icon: Inbox, tags: ['mail', 'email', 'messages'] },
  { name: 'Key', Icon: Key, tags: ['unlock', 'access', 'auth'] },
  { name: 'Lamp', Icon: Lamp, tags: ['light', 'desk'] },
  { name: 'Languages', Icon: Languages, tags: ['translate', 'learn', 'language'] },
  { name: 'Laptop', Icon: Laptop, tags: ['computer', 'work', 'remote'] },
  { name: 'Leaf', Icon: Leaf, tags: ['nature', 'plant', 'eco'] },
  { name: 'Library', Icon: Library, tags: ['books', 'study', 'read'] },
  { name: 'Lightbulb', Icon: Lightbulb, tags: ['idea', 'brainstorm', 'think'] },
  { name: 'Link', Icon: Link, tags: ['url', 'connect'] },
  { name: 'Location', Icon: MapPin, tags: ['place', 'pin', 'travel'] },
  { name: 'Mail', Icon: Mail, tags: ['email', 'inbox', 'message'] },
  { name: 'Martini', Icon: Martini, tags: ['drink', 'bar', 'happy', 'cocktail'] },
  { name: 'Megaphone', Icon: Megaphone, tags: ['announce', 'marketing', 'promo'] },
  { name: 'Message', Icon: MessageCircle, tags: ['chat', 'talk', 'sms', 'text'] },
  { name: 'Mic', Icon: Mic, tags: ['record', 'voice', 'podcast', 'talk'] },
  { name: 'Moon', Icon: Moon, tags: ['night', 'sleep', 'dark'] },
  { name: 'Mountain', Icon: Mountain, tags: ['hike', 'outdoor', 'nature'] },
  { name: 'Music', Icon: Music, tags: ['song', 'audio', 'practice'] },
  { name: 'Newspaper', Icon: Newspaper, tags: ['news', 'read', 'press'] },
  { name: 'Notebook', Icon: Notebook, tags: ['journal', 'notes', 'write'] },
  { name: 'Package', Icon: Package, tags: ['ship', 'box', 'delivery'] },
  { name: 'Palette', Icon: Palette, tags: ['art', 'color', 'design'] },
  { name: 'Party', Icon: PartyPopper, tags: ['celebrate', 'event'] },
  { name: 'Paw', Icon: PawPrint, tags: ['pet', 'animal', 'vet'] },
  { name: 'Pen', Icon: PenLine, tags: ['write', 'draft', 'journal', 'note'] },
  { name: 'PenTool', Icon: PenTool, tags: ['design', 'sketch', 'vector'] },
  { name: 'Phone', Icon: Phone, tags: ['call', 'ring', 'mobile'] },
  { name: 'PiggyBank', Icon: PiggyBank, tags: ['save', 'money', 'budget'] },
  { name: 'Pill', Icon: Pill, tags: ['medicine', 'health', 'meds'] },
  { name: 'Pin', Icon: Pin, tags: ['mark', 'fix'] },
  { name: 'Pizza', Icon: Pizza, tags: ['food', 'dinner'] },
  { name: 'Plane', Icon: Plane, tags: ['travel', 'trip', 'flight', 'airport'] },
  { name: 'Plug', Icon: Plug, tags: ['power', 'charge', 'connect'] },
  { name: 'Printer', Icon: Printer, tags: ['print', 'paper'] },
  { name: 'Puzzle', Icon: Puzzle, tags: ['problem', 'solve', 'piece'] },
  { name: 'Receipt', Icon: Receipt, tags: ['bill', 'expense', 'invoice'] },
  { name: 'Recycle', Icon: Recycle, tags: ['eco', 'reuse'] },
  { name: 'Rocket', Icon: Rocket, tags: ['launch', 'ship', 'start', 'fast'] },
  { name: 'Ruler', Icon: Ruler, tags: ['measure', 'design'] },
  { name: 'Scale', Icon: Scale, tags: ['balance', 'law', 'weigh'] },
  { name: 'Scissors', Icon: Scissors, tags: ['cut', 'trim'] },
  { name: 'Scroll', Icon: ScrollText, tags: ['document', 'doc', 'note'] },
  { name: 'Search', Icon: Search, tags: ['find', 'research', 'look'] },
  { name: 'Settings', Icon: Settings, tags: ['config', 'options'] },
  { name: 'Share', Icon: Share2, tags: ['send', 'post'] },
  { name: 'Shield', Icon: Shield, tags: ['secure', 'safe', 'protect'] },
  { name: 'ShoppingBag', Icon: ShoppingBag, tags: ['shop', 'errand', 'buy'] },
  { name: 'ShoppingCart', Icon: ShoppingCart, tags: ['shop', 'errand', 'buy', 'grocery'] },
  { name: 'Shovel', Icon: Shovel, tags: ['dig', 'garden', 'work'] },
  { name: 'Shrub', Icon: Shrub, tags: ['garden', 'plant'] },
  { name: 'Smile', Icon: Smile, tags: ['happy', 'mood', 'face'] },
  { name: 'Sparkles', Icon: Sparkles, tags: ['idea', 'magic', 'create', 'brainstorm', 'new'] },
  { name: 'Sprout', Icon: Sprout, tags: ['grow', 'plant', 'start'] },
  { name: 'Star', Icon: Star, tags: ['favorite', 'rate'] },
  { name: 'Sun', Icon: Sun, tags: ['morning', 'bright', 'weather'] },
  { name: 'Sunrise', Icon: Sunrise, tags: ['morning', 'early', 'dawn'] },
  { name: 'Sunset', Icon: Sunset, tags: ['evening', 'dusk'] },
  { name: 'Target', Icon: Target, tags: ['goal', 'focus', 'aim'] },
  { name: 'Tent', Icon: Tent, tags: ['camp', 'outdoor'] },
  { name: 'Terminal', Icon: Terminal, tags: ['code', 'dev', 'cli', 'shell'] },
  { name: 'Ticket', Icon: Ticket, tags: ['event', 'show', 'concert'] },
  { name: 'Timer', Icon: Timer, tags: ['stopwatch', 'pomodoro', 'focus'] },
  { name: 'Train', Icon: Train, tags: ['commute', 'travel'] },
  { name: 'Tree', Icon: TreePine, tags: ['nature', 'outdoor', 'park'] },
  { name: 'Trending', Icon: TrendingUp, tags: ['growth', 'analytics', 'metric'] },
  { name: 'Trophy', Icon: Trophy, tags: ['win', 'award', 'goal'] },
  { name: 'Truck', Icon: Truck, tags: ['delivery', 'ship', 'move'] },
  { name: 'Tv', Icon: Tv, tags: ['watch', 'show', 'media'] },
  { name: 'Umbrella', Icon: Umbrella, tags: ['rain', 'weather'] },
  { name: 'User', Icon: User, tags: ['profile', 'person', 'account'] },
  { name: 'Users', Icon: Users, tags: ['meet', 'standup', 'sync', 'team', 'interview', 'meeting', 'group'] },
  { name: 'Utensils', Icon: Utensils, tags: ['lunch', 'dinner', 'breakfast', 'eat', 'food', 'meal'] },
  { name: 'Video', Icon: Video, tags: ['call', 'zoom', 'meeting', 'record'] },
  { name: 'Wallet', Icon: Wallet, tags: ['money', 'finance', 'budget'] },
  { name: 'Wand', Icon: Wand2, tags: ['magic', 'create', 'auto'] },
  { name: 'Watch', Icon: Watch, tags: ['time', 'wear'] },
  { name: 'Waves', Icon: Waves, tags: ['ocean', 'beach', 'flow'] },
  { name: 'Wrench', Icon: Wrench, tags: ['fix', 'repair', 'tool', 'maintenance'] },
  { name: 'Zap', Icon: Zap, tags: ['energy', 'fast', 'quick', 'action'] },

  // ─── People & social ───────────────────────────────
  { name: 'UserCheck', Icon: UserCheck, tags: ['verified', 'approved', 'confirm', 'person'] },
  { name: 'UserPlus', Icon: UserPlus, tags: ['add', 'invite', 'new', 'person'] },
  { name: 'UserMinus', Icon: UserMinus, tags: ['remove', 'person'] },
  { name: 'UserX', Icon: UserX, tags: ['remove', 'block', 'person'] },
  { name: 'UserRoundX', Icon: UserRoundX, tags: ['remove', 'block', 'person'] },
  { name: 'UserCog', Icon: UserCog, tags: ['settings', 'profile', 'person'] },
  { name: 'Contact', Icon: Contact, tags: ['address', 'card', 'person'] },
  { name: 'Handshake', Icon: Handshake, tags: ['deal', 'agreement', 'meeting', 'partner'] },
  { name: 'PersonStanding', Icon: PersonStanding, tags: ['person', 'accessibility'] },
  { name: 'Accessibility', Icon: Accessibility, tags: ['access', 'disability', 'a11y'] },

  // ─── Body & expressions ─────────────────────────────
  { name: 'Brain', Icon: Brain, tags: ['mind', 'think', 'study', 'focus', 'memory'] },
  { name: 'Eye', Icon: Eye, tags: ['look', 'see', 'view', 'watch'] },
  { name: 'EyeOff', Icon: EyeOff, tags: ['hide', 'invisible', 'private'] },
  { name: 'Ear', Icon: Ear, tags: ['listen', 'hear', 'audio'] },
  { name: 'EarOff', Icon: EarOff, tags: ['mute', 'silence'] },
  { name: 'Glasses', Icon: Glasses, tags: ['vision', 'read', 'eyewear'] },
  { name: 'HandHeart', Icon: HandHeart, tags: ['care', 'give', 'charity', 'donate'] },
  { name: 'HandMetal', Icon: HandMetal, tags: ['rock', 'cool', 'gesture'] },
  { name: 'HandHelping', Icon: HandHelping, tags: ['help', 'support', 'assist'] },
  { name: 'Frown', Icon: Frown, tags: ['sad', 'mood', 'face'] },
  { name: 'Meh', Icon: Meh, tags: ['neutral', 'mood', 'face'] },
  { name: 'Angry', Icon: Angry, tags: ['mad', 'mood', 'face'] },
  { name: 'Annoyed', Icon: Annoyed, tags: ['frustrated', 'mood', 'face'] },
  { name: 'Laugh', Icon: Laugh, tags: ['happy', 'mood', 'face', 'joy'] },
  { name: 'Skull', Icon: Skull, tags: ['death', 'danger', 'halloween'] },

  // ─── Health & medical ─────────────────────────────
  { name: 'Stethoscope', Icon: Stethoscope, tags: ['doctor', 'health', 'medical', 'appointment'] },
  { name: 'Syringe', Icon: Syringe, tags: ['shot', 'vaccine', 'medical', 'inject'] },
  { name: 'Bandage', Icon: Bandage, tags: ['injury', 'heal', 'medical', 'first-aid'] },
  { name: 'Thermometer', Icon: Thermometer, tags: ['temperature', 'fever', 'sick', 'health'] },
  { name: 'ThermometerSnowflake', Icon: ThermometerSnowflake, tags: ['cold', 'temperature'] },
  { name: 'ThermometerSun', Icon: ThermometerSun, tags: ['hot', 'temperature'] },
  { name: 'HeartPulse', Icon: HeartPulse, tags: ['health', 'vitals', 'medical', 'pulse'] },
  { name: 'Cross', Icon: Cross, tags: ['medical', 'health', 'plus'] },
  { name: 'Hospital', Icon: Hospital, tags: ['medical', 'doctor', 'clinic', 'er'] },
  { name: 'Ambulance', Icon: Ambulance, tags: ['emergency', 'medical', 'urgent'] },
  { name: 'Bone', Icon: Bone, tags: ['skeleton', 'orthopedic', 'dog'] },
  { name: 'Dna', Icon: Dna, tags: ['genetics', 'biology', 'science'] },

  // ─── Food & drink ─────────────────────────────────
  { name: 'Wine', Icon: Wine, tags: ['drink', 'alcohol', 'dinner', 'date'] },
  { name: 'WineOff', Icon: WineOff, tags: ['sober', 'no-alcohol'] },
  { name: 'Beer', Icon: Beer, tags: ['drink', 'pub', 'alcohol', 'happy'] },
  { name: 'BeerOff', Icon: BeerOff, tags: ['sober', 'dry'] },
  { name: 'Soup', Icon: Soup, tags: ['lunch', 'food', 'meal'] },
  { name: 'Salad', Icon: Salad, tags: ['healthy', 'food', 'lunch', 'veggie'] },
  { name: 'Sandwich', Icon: Sandwich, tags: ['lunch', 'food', 'meal'] },
  { name: 'Fish', Icon: Fish, tags: ['food', 'seafood', 'pet'] },
  { name: 'Drumstick', Icon: Drumstick, tags: ['chicken', 'food', 'meat', 'dinner'] },
  { name: 'Donut', Icon: Donut, tags: ['dessert', 'snack', 'sweet'] },
  { name: 'Lollipop', Icon: Lollipop, tags: ['candy', 'sweet', 'kids'] },
  { name: 'Popcorn', Icon: Popcorn, tags: ['snack', 'movie', 'cinema'] },
  { name: 'Candy', Icon: Candy, tags: ['sweet', 'treat', 'kids'] },
  { name: 'CandyCane', Icon: CandyCane, tags: ['holiday', 'christmas', 'sweet'] },
  { name: 'CupSoda', Icon: CupSoda, tags: ['drink', 'soda', 'beverage'] },
  { name: 'GlassWater', Icon: GlassWater, tags: ['hydrate', 'drink', 'water'] },
  { name: 'Milk', Icon: Milk, tags: ['dairy', 'drink', 'breakfast'] },
  { name: 'MilkOff', Icon: MilkOff, tags: ['dairy-free', 'lactose'] },
  { name: 'CookingPot', Icon: CookingPot, tags: ['cook', 'kitchen', 'dinner', 'recipe'] },
  { name: 'HandPlatter', Icon: HandPlatter, tags: ['serve', 'food', 'meal'] },
  { name: 'Wheat', Icon: Wheat, tags: ['grain', 'bread', 'farm'] },
  { name: 'WheatOff', Icon: WheatOff, tags: ['gluten-free', 'no-wheat'] },
  { name: 'Cookie', Icon: Cookie, tags: ['snack', 'sweet', 'dessert'] },
  { name: 'Beef', Icon: Beef, tags: ['meat', 'dinner', 'food'] },
  { name: 'Ham', Icon: Ham, tags: ['meat', 'breakfast', 'food'] },
  { name: 'Citrus', Icon: Citrus, tags: ['fruit', 'lemon', 'orange'] },
  { name: 'Grape', Icon: Grape, tags: ['fruit', 'wine'] },
  { name: 'Banana', Icon: Banana, tags: ['fruit', 'snack'] },
  { name: 'Vegan', Icon: Vegan, tags: ['plant', 'diet', 'food'] },

  // ─── Weather ──────────────────────────────────────
  { name: 'CloudRain', Icon: CloudRain, tags: ['weather', 'rainy'] },
  { name: 'CloudDrizzle', Icon: CloudDrizzle, tags: ['weather', 'rain', 'light'] },
  { name: 'CloudSnow', Icon: CloudSnow, tags: ['weather', 'winter', 'snowy'] },
  { name: 'CloudLightning', Icon: CloudLightning, tags: ['weather', 'storm', 'thunder'] },
  { name: 'CloudFog', Icon: CloudFog, tags: ['weather', 'foggy', 'mist'] },
  { name: 'CloudHail', Icon: CloudHail, tags: ['weather', 'hail'] },
  { name: 'CloudSun', Icon: CloudSun, tags: ['weather', 'partly-sunny'] },
  { name: 'CloudMoon', Icon: CloudMoon, tags: ['weather', 'night'] },
  { name: 'CloudRainWind', Icon: CloudRainWind, tags: ['weather', 'storm', 'rain'] },
  { name: 'CloudOff', Icon: CloudOff, tags: ['offline', 'no-cloud'] },
  { name: 'CloudUpload', Icon: CloudUpload, tags: ['upload', 'sync', 'backup'] },
  { name: 'CloudDownload', Icon: CloudDownload, tags: ['download', 'sync'] },
  { name: 'Snowflake', Icon: Snowflake, tags: ['cold', 'winter', 'frost'] },
  { name: 'Wind', Icon: Wind, tags: ['breeze', 'air', 'weather'] },
  { name: 'Rainbow', Icon: Rainbow, tags: ['pride', 'colorful', 'after-rain'] },
  { name: 'Droplet', Icon: Droplet, tags: ['water', 'drop', 'liquid'] },
  { name: 'Droplets', Icon: Droplets, tags: ['water', 'humidity', 'liquid'] },
  { name: 'Tornado', Icon: Tornado, tags: ['storm', 'wind', 'weather'] },
  { name: 'Haze', Icon: Haze, tags: ['weather', 'fog', 'smog'] },
  { name: 'Eclipse', Icon: Eclipse, tags: ['moon', 'sun', 'astronomy'] },
  { name: 'Orbit', Icon: Orbit, tags: ['space', 'planet', 'satellite'] },

  // ─── Animals ──────────────────────────────────────
  { name: 'Bird', Icon: Bird, tags: ['animal', 'pet'] },
  { name: 'Cat', Icon: Cat, tags: ['pet', 'animal'] },
  { name: 'Rabbit', Icon: Rabbit, tags: ['pet', 'animal', 'bunny'] },
  { name: 'Rat', Icon: Rat, tags: ['rodent', 'pest', 'animal'] },
  { name: 'Turtle', Icon: Turtle, tags: ['slow', 'animal', 'pet'] },
  { name: 'Snail', Icon: Snail, tags: ['slow', 'animal'] },
  { name: 'Worm', Icon: Worm, tags: ['animal', 'garden'] },

  // ─── Plants & nature ──────────────────────────────
  { name: 'TreeDeciduous', Icon: TreeDeciduous, tags: ['nature', 'park', 'tree'] },
  { name: 'TreePalm', Icon: TreePalm, tags: ['beach', 'tropical', 'vacation'] },
  { name: 'Bloom', Icon: Flower, tags: ['garden', 'plant', 'bloom'] },
  { name: 'LeafyGreen', Icon: LeafyGreen, tags: ['veggie', 'plant', 'healthy'] },
  { name: 'Clover', Icon: Clover, tags: ['luck', 'nature', 'irish'] },

  // ─── Productivity & dev ───────────────────────────
  { name: 'GitBranch', Icon: GitBranch, tags: ['dev', 'git', 'branch', 'code'] },
  { name: 'GitCommit', Icon: GitCommitHorizontal, tags: ['dev', 'git', 'commit', 'code'] },
  { name: 'GitMerge', Icon: GitMerge, tags: ['dev', 'git', 'merge'] },
  { name: 'GitPullRequest', Icon: GitPullRequest, tags: ['dev', 'git', 'pr', 'review'] },
  { name: 'GitFork', Icon: GitFork, tags: ['dev', 'git', 'fork'] },
  { name: 'Github', Icon: Github, tags: ['dev', 'repo', 'code'] },
  { name: 'Gitlab', Icon: Gitlab, tags: ['dev', 'repo', 'code'] },
  { name: 'Codepen', Icon: Codepen, tags: ['dev', 'frontend', 'demo'] },
  { name: 'Slack', Icon: Slack, tags: ['chat', 'team', 'work'] },
  { name: 'File', Icon: File, tags: ['document', 'doc'] },
  { name: 'FileText', Icon: FileText, tags: ['document', 'doc', 'note'] },
  { name: 'FilePen', Icon: FilePen, tags: ['edit', 'document', 'write'] },
  { name: 'FileCheck', Icon: FileCheck, tags: ['done', 'approved', 'document'] },
  { name: 'FilePlus', Icon: FilePlus, tags: ['new', 'add', 'document'] },
  { name: 'FileMinus', Icon: FileMinus, tags: ['remove', 'document'] },
  { name: 'FileX', Icon: FileX, tags: ['delete', 'document'] },
  { name: 'FileSearch', Icon: FileSearch, tags: ['find', 'document'] },
  { name: 'FileCode', Icon: FileCode, tags: ['dev', 'code', 'document'] },
  { name: 'FileLock', Icon: FileLock, tags: ['secure', 'private', 'document'] },
  { name: 'FileHeart', Icon: FileHeart, tags: ['favorite', 'document'] },
  { name: 'FileImage', Icon: FileImage, tags: ['photo', 'picture', 'document'] },
  { name: 'FileVideo', Icon: FileVideo, tags: ['movie', 'document'] },
  { name: 'FileAudio', Icon: FileAudio, tags: ['sound', 'music', 'document'] },
  { name: 'FileWarning', Icon: FileWarning, tags: ['alert', 'document', 'issue'] },
  { name: 'FileSpreadsheet', Icon: FileSpreadsheet, tags: ['excel', 'data', 'sheet'] },
  { name: 'Files', Icon: Files, tags: ['documents', 'multiple'] },
  { name: 'FolderOpen', Icon: FolderOpen, tags: ['files', 'organize'] },
  { name: 'FolderPlus', Icon: FolderPlus, tags: ['new', 'add', 'folder'] },
  { name: 'FolderHeart', Icon: FolderHeart, tags: ['favorite', 'folder'] },
  { name: 'FolderLock', Icon: FolderLock, tags: ['secure', 'folder'] },
  { name: 'FolderSearch', Icon: FolderSearch, tags: ['find', 'folder'] },
  { name: 'FolderTree', Icon: FolderTree, tags: ['hierarchy', 'structure'] },
  { name: 'FolderArchive', Icon: FolderArchive, tags: ['old', 'storage'] },
  { name: 'ListTodo', Icon: ListTodo, tags: ['tasks', 'todo', 'checklist'] },
  { name: 'ListChecks', Icon: ListChecks, tags: ['done', 'checklist', 'tasks'] },
  { name: 'ListOrdered', Icon: ListOrdered, tags: ['numbered', 'list'] },
  { name: 'ListPlus', Icon: ListPlus, tags: ['add', 'list'] },
  { name: 'ListMinus', Icon: ListMinus, tags: ['remove', 'list'] },
  { name: 'ListX', Icon: ListX, tags: ['delete', 'list'] },
  { name: 'ListFilter', Icon: ListFilter, tags: ['sort', 'filter', 'list'] },
  { name: 'Workflow', Icon: Workflow, tags: ['process', 'flow', 'pipeline'] },
  { name: 'Network', Icon: Network, tags: ['connected', 'graph', 'system'] },
  { name: 'ClipboardCheck', Icon: ClipboardCheck, tags: ['done', 'tasks', 'checklist'] },
  { name: 'Boxes', Icon: Boxes, tags: ['storage', 'organize', 'stack'] },

  // ─── Travel & transport ──────────────────────────
  { name: 'Ship', Icon: Ship, tags: ['boat', 'travel', 'cargo'] },
  { name: 'Sailboat', Icon: Sailboat, tags: ['boat', 'sea', 'sail'] },
  { name: 'Bus', Icon: Bus, tags: ['transit', 'commute', 'travel'] },
  { name: 'TramFront', Icon: TramFront, tags: ['transit', 'tram', 'commute'] },
  { name: 'Luggage', Icon: Luggage, tags: ['travel', 'suitcase', 'trip'] },
  { name: 'Map', Icon: MapIcon, tags: ['navigate', 'travel', 'explore'] },
  { name: 'MapPinned', Icon: MapPinned, tags: ['location', 'place'] },
  { name: 'Globe', Icon: Globe, tags: ['world', 'earth', 'international'] },
  { name: 'Globe2', Icon: Globe2, tags: ['world', 'earth'] },
  { name: 'Backpack', Icon: Backpack, tags: ['hike', 'school', 'travel', 'bag'] },
  { name: 'Anchor', Icon: Anchor, tags: ['ship', 'sea', 'stop'] },
  { name: 'Fuel', Icon: Fuel, tags: ['gas', 'energy', 'car'] },
  { name: 'Caravan', Icon: Caravan, tags: ['camp', 'rv', 'travel'] },
  { name: 'Navigation', Icon: Navigation, tags: ['direction', 'gps'] },
  { name: 'NavigationOff', Icon: NavigationOff, tags: ['no-gps', 'offline'] },
  { name: 'Route', Icon: Route, tags: ['path', 'navigation', 'plan'] },
  { name: 'Milestone', Icon: Milestone, tags: ['progress', 'marker', 'goal'] },
  { name: 'ParkingCircle', Icon: ParkingCircle, tags: ['park', 'car', 'lot'] },
  { name: 'ParkingSquare', Icon: ParkingSquare, tags: ['park', 'car', 'lot'] },

  // ─── Money & commerce ────────────────────────────
  { name: 'Coins', Icon: Coins, tags: ['money', 'cash', 'currency'] },
  { name: 'HandCoins', Icon: HandCoins, tags: ['donate', 'give', 'money'] },
  { name: 'Landmark', Icon: Landmark, tags: ['bank', 'government', 'finance'] },
  { name: 'BadgePercent', Icon: BadgePercent, tags: ['discount', 'sale', 'offer'] },
  { name: 'Percent', Icon: Percent, tags: ['discount', 'rate', 'math'] },
  { name: 'Euro', Icon: Euro, tags: ['money', 'currency'] },
  { name: 'JapaneseYen', Icon: JapaneseYen, tags: ['money', 'yen', 'currency'] },
  { name: 'IndianRupee', Icon: IndianRupee, tags: ['money', 'rupee', 'currency'] },
  { name: 'Bitcoin', Icon: Bitcoin, tags: ['crypto', 'btc', 'currency'] },
  { name: 'TrendingDown', Icon: TrendingDown, tags: ['decline', 'loss', 'metric'] },
  { name: 'ChartPie', Icon: ChartPie, tags: ['analytics', 'breakdown'] },
  { name: 'ChartArea', Icon: ChartArea, tags: ['analytics', 'trend'] },
  { name: 'ChartBar', Icon: ChartBar, tags: ['analytics', 'stats'] },
  { name: 'ChartColumn', Icon: ChartColumn, tags: ['analytics', 'stats'] },
  { name: 'ChartCandlestick', Icon: ChartCandlestick, tags: ['stocks', 'trading', 'finance'] },
  { name: 'ShoppingBasket', Icon: ShoppingBasket, tags: ['shop', 'buy', 'cart'] },
  { name: 'DollarSign', Icon: DollarSign, tags: ['money', 'finance', 'pay'] },

  // ─── Communication ───────────────────────────────
  { name: 'MessageSquare', Icon: MessageSquare, tags: ['chat', 'sms', 'comment'] },
  { name: 'MessagesSquare', Icon: MessagesSquare, tags: ['chat', 'conversations'] },
  { name: 'MessageCircleMore', Icon: MessageCircleMore, tags: ['typing', 'chat'] },
  { name: 'MessageCircleHeart', Icon: MessageCircleHeart, tags: ['love', 'chat'] },
  { name: 'MessageCircleQuestion', Icon: MessageCircleQuestion, tags: ['help', 'question', 'chat'] },
  { name: 'AtSign', Icon: AtSign, tags: ['mention', 'email', 'tag'] },
  { name: 'Send', Icon: Send, tags: ['email', 'message', 'submit'] },
  { name: 'SendHorizontal', Icon: SendHorizontal, tags: ['send', 'submit'] },
  { name: 'Reply', Icon: Reply, tags: ['respond', 'email'] },
  { name: 'Forward', Icon: Forward, tags: ['send-on', 'email'] },
  { name: 'PhoneCall', Icon: PhoneCall, tags: ['call', 'meeting', 'ring'] },
  { name: 'PhoneIncoming', Icon: PhoneIncoming, tags: ['call', 'in'] },
  { name: 'PhoneOutgoing', Icon: PhoneOutgoing, tags: ['call', 'out'] },
  { name: 'PhoneOff', Icon: PhoneOff, tags: ['hangup', 'mute'] },
  { name: 'Voicemail', Icon: Voicemail, tags: ['message', 'recorded'] },
  { name: 'Hash', Icon: Hash, tags: ['tag', 'channel', 'number'] },
  { name: 'BellOff', Icon: BellOff, tags: ['mute', 'silent', 'dnd'] },
  { name: 'BellRing', Icon: BellRing, tags: ['alert', 'notify', 'active'] },
  { name: 'BellPlus', Icon: BellPlus, tags: ['add-notification'] },
  { name: 'BellMinus', Icon: BellMinus, tags: ['remove-notification'] },
  { name: 'BellDot', Icon: BellDot, tags: ['unread', 'notify'] },
  { name: 'Volume', Icon: Volume, tags: ['sound', 'audio'] },
  { name: 'Volume1', Icon: Volume1, tags: ['low-volume', 'audio'] },
  { name: 'Volume2', Icon: Volume2, tags: ['high-volume', 'audio'] },
  { name: 'VolumeX', Icon: VolumeX, tags: ['mute', 'silent'] },
  { name: 'Rss', Icon: Rss, tags: ['feed', 'subscribe', 'news'] },

  // ─── Tech & devices ──────────────────────────────
  { name: 'Monitor', Icon: Monitor, tags: ['screen', 'desktop', 'display'] },
  { name: 'Smartphone', Icon: Smartphone, tags: ['phone', 'mobile'] },
  { name: 'Tablet', Icon: Tablet, tags: ['ipad', 'mobile'] },
  { name: 'Server', Icon: Server, tags: ['backend', 'cloud', 'host'] },
  { name: 'ServerOff', Icon: ServerOff, tags: ['down', 'offline'] },
  { name: 'Wifi', Icon: Wifi, tags: ['internet', 'network', 'wireless'] },
  { name: 'WifiOff', Icon: WifiOff, tags: ['offline', 'no-internet'] },
  { name: 'Bluetooth', Icon: Bluetooth, tags: ['wireless', 'pair'] },
  { name: 'BluetoothOff', Icon: BluetoothOff, tags: ['disconnected'] },
  { name: 'Battery', Icon: Battery, tags: ['power', 'charge'] },
  { name: 'BatteryLow', Icon: BatteryLow, tags: ['low-power', 'charge'] },
  { name: 'BatteryMedium', Icon: BatteryMedium, tags: ['half-power'] },
  { name: 'BatteryFull', Icon: BatteryFull, tags: ['full-power'] },
  { name: 'BatteryCharging', Icon: BatteryCharging, tags: ['power-up', 'plug'] },
  { name: 'BatteryWarning', Icon: BatteryWarning, tags: ['low', 'critical'] },
  { name: 'Power', Icon: Power, tags: ['on', 'shutdown', 'turn-off'] },
  { name: 'PowerOff', Icon: PowerOff, tags: ['off', 'shutdown'] },
  { name: 'Cable', Icon: Cable, tags: ['connect', 'wire', 'plug'] },
  { name: 'Usb', Icon: Usb, tags: ['port', 'connect', 'drive'] },
  { name: 'Radio', Icon: Radio, tags: ['audio', 'signal', 'broadcast'] },
  { name: 'ScreenShare', Icon: ScreenShare, tags: ['present', 'meeting', 'share'] },
  { name: 'Cast', Icon: Cast, tags: ['stream', 'mirror', 'tv'] },
  { name: 'Airplay', Icon: Airplay, tags: ['stream', 'mirror', 'apple'] },
  { name: 'Mouse', Icon: Mouse, tags: ['click', 'cursor', 'device'] },
  { name: 'MousePointer', Icon: MousePointer, tags: ['cursor', 'click'] },
  { name: 'Pointer', Icon: Pointer, tags: ['tap', 'click', 'select'] },
  { name: 'Keyboard', Icon: Keyboard, tags: ['type', 'input', 'device'] },
  { name: 'HardDrive', Icon: HardDrive, tags: ['storage', 'disk'] },
  { name: 'Disc', Icon: Disc, tags: ['cd', 'dvd', 'media'] },
  { name: 'Disc3', Icon: Disc3, tags: ['album', 'record', 'music'] },
  { name: 'Album', Icon: Album, tags: ['music', 'record', 'collection'] },
  { name: 'MemoryStick', Icon: MemoryStick, tags: ['ram', 'storage'] },
  { name: 'Joystick', Icon: Joystick, tags: ['game', 'play', 'controller'] },

  // ─── Home & chores ───────────────────────────────
  { name: 'WashingMachine', Icon: WashingMachine, tags: ['laundry', 'clean', 'chore'] },
  { name: 'Sofa', Icon: Sofa, tags: ['couch', 'living-room', 'rest'] },
  { name: 'Bath', Icon: Bath, tags: ['shower', 'bathroom', 'clean'] },
  { name: 'Toilet', Icon: Toilet, tags: ['bathroom', 'restroom'] },
  { name: 'ShowerHead', Icon: ShowerHead, tags: ['bath', 'morning', 'clean'] },
  { name: 'BedDouble', Icon: BedDouble, tags: ['sleep', 'bedroom'] },
  { name: 'BedSingle', Icon: BedSingle, tags: ['sleep', 'bedroom'] },
  { name: 'Armchair', Icon: Armchair, tags: ['relax', 'living-room', 'chair'] },
  { name: 'Microwave', Icon: Microwave, tags: ['kitchen', 'cook', 'heat'] },
  { name: 'LampCeiling', Icon: LampCeiling, tags: ['light', 'home'] },
  { name: 'LampDesk', Icon: LampDesk, tags: ['light', 'work'] },
  { name: 'LampFloor', Icon: LampFloor, tags: ['light', 'home'] },
  { name: 'DoorOpen', Icon: DoorOpen, tags: ['enter', 'leave', 'door'] },
  { name: 'DoorClosed', Icon: DoorClosed, tags: ['locked', 'closed', 'private'] },
  { name: 'Vault', Icon: Vault, tags: ['safe', 'secure', 'storage'] },

  // ─── Tools & construction ────────────────────────
  { name: 'Drill', Icon: Drill, tags: ['tool', 'build', 'fix'] },
  { name: 'Pickaxe', Icon: Pickaxe, tags: ['mine', 'dig', 'tool'] },
  { name: 'Axe', Icon: Axe, tags: ['chop', 'tool', 'wood'] },
  { name: 'Cog', Icon: Cog, tags: ['settings', 'gear', 'config'] },
  { name: 'Settings2', Icon: Settings2, tags: ['preferences', 'config', 'sliders'] },
  { name: 'HardHat', Icon: HardHat, tags: ['construction', 'safety', 'work'] },
  { name: 'Construction', Icon: Construction, tags: ['build', 'wip', 'work-in-progress'] },
  { name: 'Magnet', Icon: Magnet, tags: ['attract', 'pull', 'physics'] },

  // ─── School & education ──────────────────────────
  { name: 'School', Icon: School, tags: ['education', 'class', 'learn'] },
  { name: 'BookA', Icon: BookA, tags: ['dictionary', 'study', 'read'] },
  { name: 'BookCheck', Icon: BookCheck, tags: ['done', 'study', 'read'] },
  { name: 'BookHeart', Icon: BookHeart, tags: ['favorite', 'read'] },
  { name: 'BookMarked', Icon: BookMarked, tags: ['saved', 'read'] },
  { name: 'BookText', Icon: BookText, tags: ['read', 'study'] },
  { name: 'BookKey', Icon: BookKey, tags: ['secret', 'guide'] },
  { name: 'BookPlus', Icon: BookPlus, tags: ['add', 'new', 'read'] },
  { name: 'BookMinus', Icon: BookMinus, tags: ['remove', 'read'] },
  { name: 'BookX', Icon: BookX, tags: ['delete', 'read'] },
  { name: 'NotebookPen', Icon: NotebookPen, tags: ['write', 'journal', 'notes'] },
  { name: 'NotebookText', Icon: NotebookText, tags: ['journal', 'notes'] },
  { name: 'NotebookTabs', Icon: NotebookTabs, tags: ['organize', 'notes'] },
  { name: 'Pencil', Icon: Pencil, tags: ['write', 'draw', 'edit'] },
  { name: 'PencilRuler', Icon: PencilRuler, tags: ['design', 'draft', 'measure'] },
  { name: 'Highlighter', Icon: Highlighter, tags: ['mark', 'study', 'emphasize'] },
  { name: 'Eraser', Icon: Eraser, tags: ['delete', 'undo', 'remove'] },
  { name: 'Atom', Icon: Atom, tags: ['science', 'physics', 'chem'] },
  { name: 'Telescope', Icon: Telescope, tags: ['astronomy', 'observe', 'space'] },
  { name: 'Microscope', Icon: Microscope, tags: ['science', 'biology', 'lab'] },
  { name: 'TestTube', Icon: TestTube, tags: ['lab', 'science', 'chem'] },
  { name: 'TestTubes', Icon: TestTubes, tags: ['lab', 'science', 'experiment'] },
  { name: 'Binoculars', Icon: Binoculars, tags: ['look', 'observe', 'spot'] },
  { name: 'Sigma', Icon: Sigma, tags: ['math', 'sum', 'stats'] },
  { name: 'Infinity', Icon: Infinity, tags: ['math', 'forever', 'loop'] },
  { name: 'Variable', Icon: Variable, tags: ['math', 'algebra'] },

  // ─── Sports & fitness ────────────────────────────
  { name: 'Medal', Icon: Medal, tags: ['win', 'achievement', 'sport'] },
  { name: 'Volleyball', Icon: Volleyball, tags: ['sport', 'play', 'beach'] },
  { name: 'Goal', Icon: Goal, tags: ['target', 'achievement'] },
  { name: 'MountainSnow', Icon: MountainSnow, tags: ['ski', 'winter', 'outdoor'] },

  // ─── Arts & creative ─────────────────────────────
  { name: 'Drum', Icon: Drum, tags: ['music', 'percussion', 'practice'] },
  { name: 'Piano', Icon: Piano, tags: ['music', 'keys', 'practice'] },
  { name: 'Music2', Icon: Music2, tags: ['song', 'audio'] },
  { name: 'Music3', Icon: Music3, tags: ['song', 'audio'] },
  { name: 'Music4', Icon: Music4, tags: ['song', 'audio'] },
  { name: 'Mic2', Icon: Mic2, tags: ['record', 'voice', 'singer'] },
  { name: 'Speaker', Icon: Speaker, tags: ['audio', 'sound', 'play'] },
  { name: 'Drama', Icon: Drama, tags: ['theater', 'masks', 'acting'] },
  { name: 'Theater', Icon: Theater, tags: ['show', 'performance', 'stage'] },
  { name: 'Ribbon', Icon: Ribbon, tags: ['award', 'gift', 'cause'] },
  { name: 'Diamond', Icon: Diamond, tags: ['premium', 'gem', 'value'] },
  { name: 'Gem', Icon: Gem, tags: ['premium', 'rare', 'value'] },
  { name: 'Gift', Icon: Gift, tags: ['present', 'birthday', 'celebrate'] },

  // ─── Time & schedule ─────────────────────────────
  { name: 'Clock', Icon: Clock, tags: ['time', 'hour'] },
  { name: 'Hourglass', Icon: Hourglass, tags: ['wait', 'time', 'patience'] },
  { name: 'History', Icon: History, tags: ['past', 'log', 'undo'] },
  { name: 'CalendarCheck', Icon: CalendarCheck, tags: ['done', 'scheduled', 'event'] },
  { name: 'CalendarClock', Icon: CalendarClock, tags: ['schedule', 'date', 'time'] },
  { name: 'CalendarDays', Icon: CalendarDays, tags: ['month', 'view', 'schedule'] },
  { name: 'CalendarHeart', Icon: CalendarHeart, tags: ['anniversary', 'date', 'special'] },
  { name: 'CalendarMinus', Icon: CalendarMinus, tags: ['cancel', 'remove-event'] },
  { name: 'CalendarPlus', Icon: CalendarPlus, tags: ['add-event', 'schedule'] },
  { name: 'CalendarRange', Icon: CalendarRange, tags: ['span', 'period'] },
  { name: 'CalendarSearch', Icon: CalendarSearch, tags: ['find-date', 'lookup'] },
  { name: 'CalendarX', Icon: CalendarX, tags: ['cancel', 'unavailable'] },
  { name: 'AlarmClockCheck', Icon: AlarmClockCheck, tags: ['set', 'alarm-done'] },
  { name: 'AlarmClockOff', Icon: AlarmClockOff, tags: ['disable', 'no-alarm'] },
  { name: 'AlarmClockPlus', Icon: AlarmClockPlus, tags: ['add-alarm'] },

  // ─── States & feedback ───────────────────────────
  { name: 'AlertCircle', Icon: AlertCircle, tags: ['warning', 'issue', 'attention'] },
  { name: 'AlertTriangle', Icon: AlertTriangle, tags: ['warning', 'danger', 'caution'] },
  { name: 'AlertOctagon', Icon: AlertOctagon, tags: ['stop', 'critical', 'danger'] },
  { name: 'Info', Icon: Info, tags: ['detail', 'help', 'about'] },
  { name: 'HelpCircle', Icon: HelpCircle, tags: ['question', 'support', 'faq'] },
  { name: 'Square', Icon: Square, tags: ['shape', 'empty', 'box'] },

  // ─── Direction & motion ──────────────────────────
  { name: 'ArrowUp', Icon: ArrowUp, tags: ['up', 'rise'] },
  { name: 'ArrowDown', Icon: ArrowDown, tags: ['down', 'fall'] },
  { name: 'ArrowLeft', Icon: ArrowLeft, tags: ['back', 'previous'] },
  { name: 'ArrowRight', Icon: ArrowRight, tags: ['next', 'forward'] },
  { name: 'ArrowUpRight', Icon: ArrowUpRight, tags: ['external', 'open'] },
  { name: 'ArrowDownRight', Icon: ArrowDownRight, tags: ['external', 'down-right'] },
  { name: 'ArrowUpLeft', Icon: ArrowUpLeft, tags: ['back', 'up-left'] },
  { name: 'ArrowDownLeft', Icon: ArrowDownLeft, tags: ['back', 'down-left'] },
  { name: 'ChevronUp', Icon: ChevronUp, tags: ['expand', 'up'] },
  { name: 'ChevronDown', Icon: ChevronDown, tags: ['expand', 'down', 'more'] },
  { name: 'ChevronLeft', Icon: ChevronLeft, tags: ['back', 'prev'] },
  { name: 'ChevronRight', Icon: ChevronRight, tags: ['next', 'forward'] },
  { name: 'CornerUpLeft', Icon: CornerUpLeft, tags: ['back', 'undo'] },
  { name: 'CornerUpRight', Icon: CornerUpRight, tags: ['redo', 'forward'] },
  { name: 'Move', Icon: Move, tags: ['drag', 'reposition'] },
  { name: 'MoveHorizontal', Icon: MoveHorizontal, tags: ['resize', 'horizontal'] },
  { name: 'MoveVertical', Icon: MoveVertical, tags: ['resize', 'vertical'] },
  { name: 'RotateCw', Icon: RotateCw, tags: ['rotate', 'redo'] },
  { name: 'RotateCcw', Icon: RotateCcw, tags: ['rotate', 'undo'] },
  { name: 'RefreshCw', Icon: RefreshCw, tags: ['reload', 'sync'] },
  { name: 'RefreshCcw', Icon: RefreshCcw, tags: ['reload', 'undo'] },
  { name: 'FlipHorizontal', Icon: FlipHorizontal, tags: ['mirror', 'flip'] },
  { name: 'FlipVertical', Icon: FlipVertical, tags: ['mirror', 'flip'] },
  { name: 'Undo', Icon: Undo, tags: ['back', 'revert'] },
  { name: 'Save', Icon: Save, tags: ['store', 'disk', 'submit'] },
  { name: 'Upload', Icon: Upload, tags: ['send', 'import'] },

  // ─── Security & privacy ──────────────────────────
  { name: 'Lock', Icon: Lock, tags: ['secure', 'private', 'locked'] },
  { name: 'Unlock', Icon: Unlock, tags: ['open', 'access'] },
  { name: 'LockKeyhole', Icon: LockKeyhole, tags: ['secure', 'private'] },
  { name: 'KeyRound', Icon: KeyRound, tags: ['auth', 'unlock'] },
  { name: 'KeySquare', Icon: KeySquare, tags: ['auth', 'unlock'] },
  { name: 'Fingerprint', Icon: Fingerprint, tags: ['biometric', 'auth', 'identity'] },
  { name: 'ScanFace', Icon: ScanFace, tags: ['face-id', 'auth', 'identity'] },
  { name: 'ShieldCheck', Icon: ShieldCheck, tags: ['verified', 'secure', 'safe'] },
  { name: 'ShieldAlert', Icon: ShieldAlert, tags: ['warning', 'security'] },
  { name: 'ShieldX', Icon: ShieldX, tags: ['unprotected', 'unsafe'] },
  { name: 'ShieldOff', Icon: ShieldOff, tags: ['disabled', 'unprotected'] },

  // ─── Misc useful ─────────────────────────────────
  { name: 'Tag', Icon: Tag, tags: ['label', 'category', 'price'] },
  { name: 'Tags', Icon: Tags, tags: ['labels', 'categories'] },
  { name: 'BookmarkCheck', Icon: BookmarkCheck, tags: ['saved', 'done'] },
  { name: 'BookmarkPlus', Icon: BookmarkPlus, tags: ['add', 'save'] },
  { name: 'BookmarkMinus', Icon: BookmarkMinus, tags: ['remove'] },
  { name: 'BookmarkX', Icon: BookmarkX, tags: ['delete'] },
  { name: 'Sticker', Icon: Sticker, tags: ['fun', 'label', 'decorate'] },
  { name: 'StickyNote', Icon: StickyNote, tags: ['memo', 'reminder', 'note'] },
  { name: 'Paperclip', Icon: Paperclip, tags: ['attach', 'file', 'clip'] },
  { name: 'Crosshair', Icon: Crosshair, tags: ['target', 'aim', 'focus'] },
  { name: 'Focus', Icon: Focus, tags: ['target', 'aim', 'sharp'] },
  { name: 'FountainPen', Icon: Pen, tags: ['write', 'edit'] },
  { name: 'Building2Alt', Icon: Building, tags: ['office', 'tower'] },

  // ─── Extended library (auto-generated from lucide-react) ───
  { name: 'AArrowDown', Icon: AArrowDown, tags: ['arrow', 'down'] },
  { name: 'AArrowUp', Icon: AArrowUp, tags: ['arrow'] },
  { name: 'ALargeSmall', Icon: ALargeSmall, tags: ['large', 'small'] },
  { name: 'ActivitySquare', Icon: ActivitySquare, tags: ['activity', 'square'] },
  { name: 'AirVent', Icon: AirVent, tags: ['air', 'vent'] },
  { name: 'AlarmCheck', Icon: AlarmCheck, tags: ['alarm', 'check'] },
  { name: 'AlarmClockMinus', Icon: AlarmClockMinus, tags: ['alarm', 'clock', 'minus'] },
  { name: 'AlarmSmoke', Icon: AlarmSmoke, tags: ['alarm', 'smoke'] },
  { name: 'AlignCenter', Icon: AlignCenter, tags: ['align', 'center'] },
  { name: 'AlignCenterHorizontal', Icon: AlignCenterHorizontal, tags: ['align', 'center', 'horizontal'] },
  { name: 'AlignCenterVertical', Icon: AlignCenterVertical, tags: ['align', 'center', 'vertical'] },
  { name: 'AlignEndHorizontal', Icon: AlignEndHorizontal, tags: ['align', 'end', 'horizontal'] },
  { name: 'AlignEndVertical', Icon: AlignEndVertical, tags: ['align', 'end', 'vertical'] },
  { name: 'AlignHorizontalDistributeCenter', Icon: AlignHorizontalDistributeCenter, tags: ['align', 'horizontal', 'distribute', 'center'] },
  { name: 'AlignHorizontalDistributeEnd', Icon: AlignHorizontalDistributeEnd, tags: ['align', 'horizontal', 'distribute', 'end'] },
  { name: 'AlignHorizontalDistributeStart', Icon: AlignHorizontalDistributeStart, tags: ['align', 'horizontal', 'distribute', 'start'] },
  { name: 'AlignHorizontalJustifyCenter', Icon: AlignHorizontalJustifyCenter, tags: ['align', 'horizontal', 'justify', 'center'] },
  { name: 'AlignHorizontalJustifyEnd', Icon: AlignHorizontalJustifyEnd, tags: ['align', 'horizontal', 'justify', 'end'] },
  { name: 'AlignHorizontalJustifyStart', Icon: AlignHorizontalJustifyStart, tags: ['align', 'horizontal', 'justify', 'start'] },
  { name: 'AlignHorizontalSpaceAround', Icon: AlignHorizontalSpaceAround, tags: ['align', 'horizontal', 'space', 'around'] },
  { name: 'AlignHorizontalSpaceBetween', Icon: AlignHorizontalSpaceBetween, tags: ['align', 'horizontal', 'space', 'between'] },
  { name: 'AlignJustify', Icon: AlignJustify, tags: ['align', 'justify'] },
  { name: 'AlignLeft', Icon: AlignLeft, tags: ['align', 'left'] },
  { name: 'AlignRight', Icon: AlignRight, tags: ['align', 'right'] },
  { name: 'AlignStartHorizontal', Icon: AlignStartHorizontal, tags: ['align', 'start', 'horizontal'] },
  { name: 'AlignStartVertical', Icon: AlignStartVertical, tags: ['align', 'start', 'vertical'] },
  { name: 'AlignVerticalDistributeCenter', Icon: AlignVerticalDistributeCenter, tags: ['align', 'vertical', 'distribute', 'center'] },
  { name: 'AlignVerticalDistributeEnd', Icon: AlignVerticalDistributeEnd, tags: ['align', 'vertical', 'distribute', 'end'] },
  { name: 'AlignVerticalDistributeStart', Icon: AlignVerticalDistributeStart, tags: ['align', 'vertical', 'distribute', 'start'] },
  { name: 'AlignVerticalJustifyCenter', Icon: AlignVerticalJustifyCenter, tags: ['align', 'vertical', 'justify', 'center'] },
  { name: 'AlignVerticalJustifyEnd', Icon: AlignVerticalJustifyEnd, tags: ['align', 'vertical', 'justify', 'end'] },
  { name: 'AlignVerticalJustifyStart', Icon: AlignVerticalJustifyStart, tags: ['align', 'vertical', 'justify', 'start'] },
  { name: 'AlignVerticalSpaceAround', Icon: AlignVerticalSpaceAround, tags: ['align', 'vertical', 'space', 'around'] },
  { name: 'AlignVerticalSpaceBetween', Icon: AlignVerticalSpaceBetween, tags: ['align', 'vertical', 'space', 'between'] },
  { name: 'Ampersand', Icon: Ampersand, tags: ['ampersand'] },
  { name: 'Ampersands', Icon: Ampersands, tags: ['ampersands'] },
  { name: 'Amphora', Icon: Amphora, tags: ['amphora'] },
  { name: 'Antenna', Icon: Antenna, tags: ['antenna'] },
  { name: 'Anvil', Icon: Anvil, tags: ['anvil'] },
  { name: 'Aperture', Icon: Aperture, tags: ['aperture'] },
  { name: 'AppWindow', Icon: AppWindow, tags: ['app', 'window'] },
  { name: 'AppWindowMac', Icon: AppWindowMac, tags: ['app', 'window', 'mac'] },
  { name: 'ArchiveRestore', Icon: ArchiveRestore, tags: ['archive', 'restore'] },
  { name: 'ArchiveX', Icon: ArchiveX, tags: ['archive'] },
  { name: 'AreaChart', Icon: AreaChart, tags: ['area', 'chart'] },
  { name: 'ArrowBigDown', Icon: ArrowBigDown, tags: ['arrow', 'big', 'down'] },
  { name: 'ArrowBigDownDash', Icon: ArrowBigDownDash, tags: ['arrow', 'big', 'down', 'dash'] },
  { name: 'ArrowBigLeft', Icon: ArrowBigLeft, tags: ['arrow', 'big', 'left'] },
  { name: 'ArrowBigLeftDash', Icon: ArrowBigLeftDash, tags: ['arrow', 'big', 'left', 'dash'] },
  { name: 'ArrowBigRight', Icon: ArrowBigRight, tags: ['arrow', 'big', 'right'] },
  { name: 'ArrowBigRightDash', Icon: ArrowBigRightDash, tags: ['arrow', 'big', 'right', 'dash'] },
  { name: 'ArrowBigUp', Icon: ArrowBigUp, tags: ['arrow', 'big'] },
  { name: 'ArrowBigUpDash', Icon: ArrowBigUpDash, tags: ['arrow', 'big', 'dash'] },
  { name: 'ArrowDown01', Icon: ArrowDown01, tags: ['arrow', 'down01'] },
  { name: 'ArrowDown10', Icon: ArrowDown10, tags: ['arrow', 'down10'] },
  { name: 'ArrowDownAZ', Icon: ArrowDownAZ, tags: ['arrow', 'down'] },
  { name: 'ArrowDownCircle', Icon: ArrowDownCircle, tags: ['arrow', 'down', 'circle'] },
  { name: 'ArrowDownFromLine', Icon: ArrowDownFromLine, tags: ['arrow', 'down', 'from', 'line'] },
  { name: 'ArrowDownLeftFromCircle', Icon: ArrowDownLeftFromCircle, tags: ['arrow', 'down', 'left', 'from', 'circle'] },
  { name: 'ArrowDownLeftFromSquare', Icon: ArrowDownLeftFromSquare, tags: ['arrow', 'down', 'left', 'from', 'square'] },
  { name: 'ArrowDownLeftSquare', Icon: ArrowDownLeftSquare, tags: ['arrow', 'down', 'left', 'square'] },
  { name: 'ArrowDownNarrowWide', Icon: ArrowDownNarrowWide, tags: ['arrow', 'down', 'narrow', 'wide'] },
  { name: 'ArrowDownRightFromCircle', Icon: ArrowDownRightFromCircle, tags: ['arrow', 'down', 'right', 'from', 'circle'] },
  { name: 'ArrowDownRightFromSquare', Icon: ArrowDownRightFromSquare, tags: ['arrow', 'down', 'right', 'from', 'square'] },
  { name: 'ArrowDownRightSquare', Icon: ArrowDownRightSquare, tags: ['arrow', 'down', 'right', 'square'] },
  { name: 'ArrowDownSquare', Icon: ArrowDownSquare, tags: ['arrow', 'down', 'square'] },
  { name: 'ArrowDownToDot', Icon: ArrowDownToDot, tags: ['arrow', 'down', 'dot'] },
  { name: 'ArrowDownToLine', Icon: ArrowDownToLine, tags: ['arrow', 'down', 'line'] },
  { name: 'ArrowDownUp', Icon: ArrowDownUp, tags: ['arrow', 'down'] },
  { name: 'ArrowDownWideNarrow', Icon: ArrowDownWideNarrow, tags: ['arrow', 'down', 'wide', 'narrow'] },
  { name: 'ArrowDownZA', Icon: ArrowDownZA, tags: ['arrow', 'down'] },
  { name: 'ArrowLeftCircle', Icon: ArrowLeftCircle, tags: ['arrow', 'left', 'circle'] },
  { name: 'ArrowLeftFromLine', Icon: ArrowLeftFromLine, tags: ['arrow', 'left', 'from', 'line'] },
  { name: 'ArrowLeftRight', Icon: ArrowLeftRight, tags: ['arrow', 'left', 'right'] },
  { name: 'ArrowLeftSquare', Icon: ArrowLeftSquare, tags: ['arrow', 'left', 'square'] },
  { name: 'ArrowLeftToLine', Icon: ArrowLeftToLine, tags: ['arrow', 'left', 'line'] },
  { name: 'ArrowRightCircle', Icon: ArrowRightCircle, tags: ['arrow', 'right', 'circle'] },
  { name: 'ArrowRightFromLine', Icon: ArrowRightFromLine, tags: ['arrow', 'right', 'from', 'line'] },
  { name: 'ArrowRightLeft', Icon: ArrowRightLeft, tags: ['arrow', 'right', 'left'] },
  { name: 'ArrowRightSquare', Icon: ArrowRightSquare, tags: ['arrow', 'right', 'square'] },
  { name: 'ArrowRightToLine', Icon: ArrowRightToLine, tags: ['arrow', 'right', 'line'] },
  { name: 'ArrowUp01', Icon: ArrowUp01, tags: ['arrow', 'up01'] },
  { name: 'ArrowUp10', Icon: ArrowUp10, tags: ['arrow', 'up10'] },
  { name: 'ArrowUpAZ', Icon: ArrowUpAZ, tags: ['arrow'] },
  { name: 'ArrowUpCircle', Icon: ArrowUpCircle, tags: ['arrow', 'circle'] },
  { name: 'ArrowUpDown', Icon: ArrowUpDown, tags: ['arrow', 'down'] },
  { name: 'ArrowUpFromDot', Icon: ArrowUpFromDot, tags: ['arrow', 'from', 'dot'] },
  { name: 'ArrowUpFromLine', Icon: ArrowUpFromLine, tags: ['arrow', 'from', 'line'] },
  { name: 'ArrowUpLeftFromCircle', Icon: ArrowUpLeftFromCircle, tags: ['arrow', 'left', 'from', 'circle'] },
  { name: 'ArrowUpLeftFromSquare', Icon: ArrowUpLeftFromSquare, tags: ['arrow', 'left', 'from', 'square'] },
  { name: 'ArrowUpLeftSquare', Icon: ArrowUpLeftSquare, tags: ['arrow', 'left', 'square'] },
  { name: 'ArrowUpNarrowWide', Icon: ArrowUpNarrowWide, tags: ['arrow', 'narrow', 'wide'] },
  { name: 'ArrowUpRightFromCircle', Icon: ArrowUpRightFromCircle, tags: ['arrow', 'right', 'from', 'circle'] },
  { name: 'ArrowUpRightFromSquare', Icon: ArrowUpRightFromSquare, tags: ['arrow', 'right', 'from', 'square'] },
  { name: 'ArrowUpRightSquare', Icon: ArrowUpRightSquare, tags: ['arrow', 'right', 'square'] },
  { name: 'ArrowUpSquare', Icon: ArrowUpSquare, tags: ['arrow', 'square'] },
  { name: 'ArrowUpToLine', Icon: ArrowUpToLine, tags: ['arrow', 'line'] },
  { name: 'ArrowUpWideNarrow', Icon: ArrowUpWideNarrow, tags: ['arrow', 'wide', 'narrow'] },
  { name: 'ArrowUpZA', Icon: ArrowUpZA, tags: ['arrow'] },
  { name: 'ArrowsUpFromLine', Icon: ArrowsUpFromLine, tags: ['arrows', 'from', 'line'] },
  { name: 'Asterisk', Icon: Asterisk, tags: ['asterisk'] },
  { name: 'AsteriskSquare', Icon: AsteriskSquare, tags: ['asterisk', 'square'] },
  { name: 'AudioLines', Icon: AudioLines, tags: ['audio', 'lines'] },
  { name: 'AudioWaveform', Icon: AudioWaveform, tags: ['audio', 'waveform'] },
  { name: 'Axis3D', Icon: Axis3D, tags: ['axis3d'] },
  { name: 'Badge', Icon: Badge, tags: ['badge'] },
  { name: 'BadgeAlert', Icon: BadgeAlert, tags: ['badge', 'alert'] },
  { name: 'BadgeCent', Icon: BadgeCent, tags: ['badge', 'cent'] },
  { name: 'BadgeCheck', Icon: BadgeCheck, tags: ['badge', 'check'] },
  { name: 'BadgeDollarSign', Icon: BadgeDollarSign, tags: ['badge', 'dollar', 'sign'] },
  { name: 'BadgeEuro', Icon: BadgeEuro, tags: ['badge', 'euro'] },
  { name: 'BadgeHelp', Icon: BadgeHelp, tags: ['badge', 'help'] },
  { name: 'BadgeIndianRupee', Icon: BadgeIndianRupee, tags: ['badge', 'indian', 'rupee'] },
  { name: 'BadgeInfo', Icon: BadgeInfo, tags: ['badge', 'info'] },
  { name: 'BadgeJapaneseYen', Icon: BadgeJapaneseYen, tags: ['badge', 'japanese', 'yen'] },
  { name: 'BadgeMinus', Icon: BadgeMinus, tags: ['badge', 'minus'] },
  { name: 'BadgePlus', Icon: BadgePlus, tags: ['badge', 'plus'] },
  { name: 'BadgePoundSterling', Icon: BadgePoundSterling, tags: ['badge', 'pound', 'sterling'] },
  { name: 'BadgeRussianRuble', Icon: BadgeRussianRuble, tags: ['badge', 'russian', 'ruble'] },
  { name: 'BadgeSwissFranc', Icon: BadgeSwissFranc, tags: ['badge', 'swiss', 'franc'] },
  { name: 'BadgeX', Icon: BadgeX, tags: ['badge'] },
  { name: 'BaggageClaim', Icon: BaggageClaim, tags: ['baggage', 'claim'] },
  { name: 'Ban', Icon: Ban, tags: ['ban'] },
  { name: 'BarChart2', Icon: BarChart2, tags: ['bar', 'chart2'] },
  { name: 'BarChart4', Icon: BarChart4, tags: ['bar', 'chart4'] },
  { name: 'BarChartBig', Icon: BarChartBig, tags: ['bar', 'chart', 'big'] },
  { name: 'BarChartHorizontal', Icon: BarChartHorizontal, tags: ['bar', 'chart', 'horizontal'] },
  { name: 'BarChartHorizontalBig', Icon: BarChartHorizontalBig, tags: ['bar', 'chart', 'horizontal', 'big'] },
  { name: 'Barcode', Icon: Barcode, tags: ['barcode'] },
  { name: 'Baseline', Icon: Baseline, tags: ['baseline'] },
  { name: 'Bean', Icon: Bean, tags: ['bean'] },
  { name: 'BeanOff', Icon: BeanOff, tags: ['bean', 'off'] },
  { name: 'BellElectric', Icon: BellElectric, tags: ['bell', 'electric'] },
  { name: 'BetweenHorizonalEnd', Icon: BetweenHorizonalEnd, tags: ['between', 'horizonal', 'end'] },
  { name: 'BetweenHorizonalStart', Icon: BetweenHorizonalStart, tags: ['between', 'horizonal', 'start'] },
  { name: 'BetweenVerticalEnd', Icon: BetweenVerticalEnd, tags: ['between', 'vertical', 'end'] },
  { name: 'BetweenVerticalStart', Icon: BetweenVerticalStart, tags: ['between', 'vertical', 'start'] },
  { name: 'BicepsFlexed', Icon: BicepsFlexed, tags: ['biceps', 'flexed'] },
  { name: 'Binary', Icon: Binary, tags: ['binary'] },
  { name: 'Biohazard', Icon: Biohazard, tags: ['biohazard'] },
  { name: 'Blend', Icon: Blend, tags: ['blend'] },
  { name: 'Blinds', Icon: Blinds, tags: ['blinds'] },
  { name: 'Blocks', Icon: Blocks, tags: ['blocks'] },
  { name: 'BluetoothConnected', Icon: BluetoothConnected, tags: ['bluetooth', 'connected'] },
  { name: 'BluetoothSearching', Icon: BluetoothSearching, tags: ['bluetooth', 'searching'] },
  { name: 'Bold', Icon: Bold, tags: ['bold'] },
  { name: 'Bolt', Icon: Bolt, tags: ['bolt'] },
  { name: 'Bomb', Icon: Bomb, tags: ['bomb'] },
  { name: 'Book', Icon: Book, tags: ['book'] },
  { name: 'BookAudio', Icon: BookAudio, tags: ['book', 'audio'] },
  { name: 'BookCopy', Icon: BookCopy, tags: ['book', 'copy'] },
  { name: 'BookDashed', Icon: BookDashed, tags: ['book', 'dashed'] },
  { name: 'BookDown', Icon: BookDown, tags: ['book', 'down'] },
  { name: 'BookHeadphones', Icon: BookHeadphones, tags: ['book', 'headphones'] },
  { name: 'BookImage', Icon: BookImage, tags: ['book', 'image'] },
  { name: 'BookLock', Icon: BookLock, tags: ['book', 'lock'] },
  { name: 'BookOpenCheck', Icon: BookOpenCheck, tags: ['book', 'open', 'check'] },
  { name: 'BookOpenText', Icon: BookOpenText, tags: ['book', 'open', 'text'] },
  { name: 'BookType', Icon: BookType, tags: ['book', 'type'] },
  { name: 'BookUp', Icon: BookUp, tags: ['book'] },
  { name: 'BookUp2', Icon: BookUp2, tags: ['book', 'up2'] },
  { name: 'BookUser', Icon: BookUser, tags: ['book', 'user'] },
  { name: 'BoomBox', Icon: BoomBox, tags: ['boom', 'box'] },
  { name: 'Bot', Icon: Bot, tags: ['bot'] },
  { name: 'BotMessageSquare', Icon: BotMessageSquare, tags: ['bot', 'message', 'square'] },
  { name: 'BotOff', Icon: BotOff, tags: ['bot', 'off'] },
  { name: 'Box', Icon: Box, tags: ['box'] },
  { name: 'BoxSelect', Icon: BoxSelect, tags: ['box', 'select'] },
  { name: 'Braces', Icon: Braces, tags: ['braces'] },
  { name: 'Brackets', Icon: Brackets, tags: ['brackets'] },
  { name: 'BrainCircuit', Icon: BrainCircuit, tags: ['brain', 'circuit'] },
  { name: 'BrainCog', Icon: BrainCog, tags: ['brain', 'cog'] },
  { name: 'BrickWall', Icon: BrickWall, tags: ['brick', 'wall'] },
  { name: 'BriefcaseBusiness', Icon: BriefcaseBusiness, tags: ['briefcase', 'business'] },
  { name: 'BriefcaseConveyorBelt', Icon: BriefcaseConveyorBelt, tags: ['briefcase', 'conveyor', 'belt'] },
  { name: 'BriefcaseMedical', Icon: BriefcaseMedical, tags: ['briefcase', 'medical'] },
  { name: 'BringToFront', Icon: BringToFront, tags: ['bring', 'front'] },
  { name: 'BugOff', Icon: BugOff, tags: ['bug', 'off'] },
  { name: 'BugPlay', Icon: BugPlay, tags: ['bug', 'play'] },
  { name: 'BusFront', Icon: BusFront, tags: ['bus', 'front'] },
  { name: 'CableCar', Icon: CableCar, tags: ['cable', 'car'] },
  { name: 'CakeSlice', Icon: CakeSlice, tags: ['cake', 'slice'] },
  { name: 'Calendar1', Icon: Calendar1, tags: ['calendar1'] },
  { name: 'CalendarArrowDown', Icon: CalendarArrowDown, tags: ['calendar', 'arrow', 'down'] },
  { name: 'CalendarArrowUp', Icon: CalendarArrowUp, tags: ['calendar', 'arrow'] },
  { name: 'CalendarCheck2', Icon: CalendarCheck2, tags: ['calendar', 'check2'] },
  { name: 'CalendarCog', Icon: CalendarCog, tags: ['calendar', 'cog'] },
  { name: 'CalendarFold', Icon: CalendarFold, tags: ['calendar', 'fold'] },
  { name: 'CalendarMinus2', Icon: CalendarMinus2, tags: ['calendar', 'minus2'] },
  { name: 'CalendarOff', Icon: CalendarOff, tags: ['calendar', 'off'] },
  { name: 'CalendarPlus2', Icon: CalendarPlus2, tags: ['calendar', 'plus2'] },
  { name: 'CalendarSync', Icon: CalendarSync, tags: ['calendar', 'sync'] },
  { name: 'CalendarX2', Icon: CalendarX2, tags: ['calendar'] },
  { name: 'CameraOff', Icon: CameraOff, tags: ['camera', 'off'] },
  { name: 'CandlestickChart', Icon: CandlestickChart, tags: ['candlestick', 'chart'] },
  { name: 'CandyOff', Icon: CandyOff, tags: ['candy', 'off'] },
  { name: 'Cannabis', Icon: Cannabis, tags: ['cannabis'] },
  { name: 'Captions', Icon: Captions, tags: ['captions'] },
  { name: 'CaptionsOff', Icon: CaptionsOff, tags: ['captions', 'off'] },
  { name: 'CarFront', Icon: CarFront, tags: ['car', 'front'] },
  { name: 'CarTaxiFront', Icon: CarTaxiFront, tags: ['car', 'taxi', 'front'] },
  { name: 'CaseLower', Icon: CaseLower, tags: ['case', 'lower'] },
  { name: 'CaseSensitive', Icon: CaseSensitive, tags: ['case', 'sensitive'] },
  { name: 'CaseUpper', Icon: CaseUpper, tags: ['case', 'upper'] },
  { name: 'CassetteTape', Icon: CassetteTape, tags: ['cassette', 'tape'] },
  { name: 'Castle', Icon: Castle, tags: ['castle'] },
  { name: 'Cctv', Icon: Cctv, tags: ['cctv'] },
  { name: 'ChartBarDecreasing', Icon: ChartBarDecreasing, tags: ['chart', 'bar', 'decreasing'] },
  { name: 'ChartBarIncreasing', Icon: ChartBarIncreasing, tags: ['chart', 'bar', 'increasing'] },
  { name: 'ChartBarStacked', Icon: ChartBarStacked, tags: ['chart', 'bar', 'stacked'] },
  { name: 'ChartColumnDecreasing', Icon: ChartColumnDecreasing, tags: ['chart', 'column', 'decreasing'] },
  { name: 'ChartColumnStacked', Icon: ChartColumnStacked, tags: ['chart', 'column', 'stacked'] },
  { name: 'ChartGantt', Icon: ChartGantt, tags: ['chart', 'gantt'] },
  { name: 'ChartNetwork', Icon: ChartNetwork, tags: ['chart', 'network'] },
  { name: 'ChartNoAxesColumnDecreasing', Icon: ChartNoAxesColumnDecreasing, tags: ['chart', 'axes', 'column', 'decreasing'] },
  { name: 'ChartNoAxesCombined', Icon: ChartNoAxesCombined, tags: ['chart', 'axes', 'combined'] },
  { name: 'ChartNoAxesGantt', Icon: ChartNoAxesGantt, tags: ['chart', 'axes', 'gantt'] },
  { name: 'ChartScatter', Icon: ChartScatter, tags: ['chart', 'scatter'] },
  { name: 'ChartSpline', Icon: ChartSpline, tags: ['chart', 'spline'] },
  { name: 'Check', Icon: Check, tags: ['check'] },
  { name: 'CheckCheck', Icon: CheckCheck, tags: ['check'] },
  { name: 'CheckCircle', Icon: CheckCircle, tags: ['check', 'circle'] },
  { name: 'CheckCircle2', Icon: CheckCircle2, tags: ['check', 'circle2'] },
  { name: 'CheckSquare', Icon: CheckSquare, tags: ['check', 'square'] },
  { name: 'CheckSquare2', Icon: CheckSquare2, tags: ['check', 'square2'] },
  { name: 'ChevronDownCircle', Icon: ChevronDownCircle, tags: ['chevron', 'down', 'circle'] },
  { name: 'ChevronDownSquare', Icon: ChevronDownSquare, tags: ['chevron', 'down', 'square'] },
  { name: 'ChevronFirst', Icon: ChevronFirst, tags: ['chevron', 'first'] },
  { name: 'ChevronLast', Icon: ChevronLast, tags: ['chevron', 'last'] },
  { name: 'ChevronLeftCircle', Icon: ChevronLeftCircle, tags: ['chevron', 'left', 'circle'] },
  { name: 'ChevronLeftSquare', Icon: ChevronLeftSquare, tags: ['chevron', 'left', 'square'] },
  { name: 'ChevronRightCircle', Icon: ChevronRightCircle, tags: ['chevron', 'right', 'circle'] },
  { name: 'ChevronRightSquare', Icon: ChevronRightSquare, tags: ['chevron', 'right', 'square'] },
  { name: 'ChevronUpCircle', Icon: ChevronUpCircle, tags: ['chevron', 'circle'] },
  { name: 'ChevronUpSquare', Icon: ChevronUpSquare, tags: ['chevron', 'square'] },
  { name: 'ChevronsDown', Icon: ChevronsDown, tags: ['chevrons', 'down'] },
  { name: 'ChevronsDownUp', Icon: ChevronsDownUp, tags: ['chevrons', 'down'] },
  { name: 'ChevronsLeft', Icon: ChevronsLeft, tags: ['chevrons', 'left'] },
  { name: 'ChevronsLeftRight', Icon: ChevronsLeftRight, tags: ['chevrons', 'left', 'right'] },
  { name: 'ChevronsLeftRightEllipsis', Icon: ChevronsLeftRightEllipsis, tags: ['chevrons', 'left', 'right', 'ellipsis'] },
  { name: 'ChevronsRight', Icon: ChevronsRight, tags: ['chevrons', 'right'] },
  { name: 'ChevronsRightLeft', Icon: ChevronsRightLeft, tags: ['chevrons', 'right', 'left'] },
  { name: 'ChevronsUp', Icon: ChevronsUp, tags: ['chevrons'] },
  { name: 'ChevronsUpDown', Icon: ChevronsUpDown, tags: ['chevrons', 'down'] },
  { name: 'Chrome', Icon: Chrome, tags: ['chrome'] },
  { name: 'Church', Icon: Church, tags: ['church'] },
  { name: 'CigaretteOff', Icon: CigaretteOff, tags: ['cigarette', 'off'] },
  { name: 'Circle', Icon: Circle, tags: ['circle'] },
  { name: 'CircleDashed', Icon: CircleDashed, tags: ['circle', 'dashed'] },
  { name: 'CircleDivide', Icon: CircleDivide, tags: ['circle', 'divide'] },
  { name: 'CircleDollarSign', Icon: CircleDollarSign, tags: ['circle', 'dollar', 'sign'] },
  { name: 'CircleDot', Icon: CircleDot, tags: ['circle', 'dot'] },
  { name: 'CircleDotDashed', Icon: CircleDotDashed, tags: ['circle', 'dot', 'dashed'] },
  { name: 'CircleEllipsis', Icon: CircleEllipsis, tags: ['circle', 'ellipsis'] },
  { name: 'CircleEqual', Icon: CircleEqual, tags: ['circle', 'equal'] },
  { name: 'CircleFadingArrowUp', Icon: CircleFadingArrowUp, tags: ['circle', 'fading', 'arrow'] },
  { name: 'CircleFadingPlus', Icon: CircleFadingPlus, tags: ['circle', 'fading', 'plus'] },
  { name: 'CircleGauge', Icon: CircleGauge, tags: ['circle', 'gauge'] },
  { name: 'CircleHelp', Icon: CircleHelp, tags: ['circle', 'help'] },
  { name: 'CircleMinus', Icon: CircleMinus, tags: ['circle', 'minus'] },
  { name: 'CircleOff', Icon: CircleOff, tags: ['circle', 'off'] },
  { name: 'CircleParking', Icon: CircleParking, tags: ['circle', 'parking'] },
  { name: 'CircleParkingOff', Icon: CircleParkingOff, tags: ['circle', 'parking', 'off'] },
  { name: 'CirclePause', Icon: CirclePause, tags: ['circle', 'pause'] },
  { name: 'CirclePercent', Icon: CirclePercent, tags: ['circle', 'percent'] },
  { name: 'CirclePlay', Icon: CirclePlay, tags: ['circle', 'play'] },
  { name: 'CirclePlus', Icon: CirclePlus, tags: ['circle', 'plus'] },
  { name: 'CirclePower', Icon: CirclePower, tags: ['circle', 'power'] },
  { name: 'CircleSlash', Icon: CircleSlash, tags: ['circle', 'slash'] },
  { name: 'CircleSlash2', Icon: CircleSlash2, tags: ['circle', 'slash2'] },
  { name: 'CircleStop', Icon: CircleStop, tags: ['circle', 'stop'] },
  { name: 'CircleUser', Icon: CircleUser, tags: ['circle', 'user'] },
  { name: 'CircleUserRound', Icon: CircleUserRound, tags: ['circle', 'user', 'round'] },
  { name: 'CircleX', Icon: CircleX, tags: ['circle'] },
  { name: 'CircuitBoard', Icon: CircuitBoard, tags: ['circuit', 'board'] },
  { name: 'ClipboardCopy', Icon: ClipboardCopy, tags: ['clipboard', 'copy'] },
  { name: 'ClipboardEdit', Icon: ClipboardEdit, tags: ['clipboard', 'edit'] },
  { name: 'ClipboardMinus', Icon: ClipboardMinus, tags: ['clipboard', 'minus'] },
  { name: 'ClipboardPaste', Icon: ClipboardPaste, tags: ['clipboard', 'paste'] },
  { name: 'ClipboardPenLine', Icon: ClipboardPenLine, tags: ['clipboard', 'pen', 'line'] },
  { name: 'ClipboardPlus', Icon: ClipboardPlus, tags: ['clipboard', 'plus'] },
  { name: 'ClipboardType', Icon: ClipboardType, tags: ['clipboard', 'type'] },
  { name: 'ClipboardX', Icon: ClipboardX, tags: ['clipboard'] },
  { name: 'Clock1', Icon: Clock1, tags: ['clock1'] },
  { name: 'Clock10', Icon: Clock10, tags: ['clock10'] },
  { name: 'Clock11', Icon: Clock11, tags: ['clock11'] },
  { name: 'Clock12', Icon: Clock12, tags: ['clock12'] },
  { name: 'Clock2', Icon: Clock2, tags: ['clock2'] },
  { name: 'Clock3', Icon: Clock3, tags: ['clock3'] },
  { name: 'Clock4', Icon: Clock4, tags: ['clock4'] },
  { name: 'Clock5', Icon: Clock5, tags: ['clock5'] },
  { name: 'Clock6', Icon: Clock6, tags: ['clock6'] },
  { name: 'Clock7', Icon: Clock7, tags: ['clock7'] },
  { name: 'Clock8', Icon: Clock8, tags: ['clock8'] },
  { name: 'Clock9', Icon: Clock9, tags: ['clock9'] },
  { name: 'ClockAlert', Icon: ClockAlert, tags: ['clock', 'alert'] },
  { name: 'ClockArrowDown', Icon: ClockArrowDown, tags: ['clock', 'arrow', 'down'] },
  { name: 'ClockArrowUp', Icon: ClockArrowUp, tags: ['clock', 'arrow'] },
  { name: 'CloudAlert', Icon: CloudAlert, tags: ['cloud', 'alert'] },
  { name: 'CloudCog', Icon: CloudCog, tags: ['cloud', 'cog'] },
  { name: 'CloudMoonRain', Icon: CloudMoonRain, tags: ['cloud', 'moon', 'rain'] },
  { name: 'CloudSunRain', Icon: CloudSunRain, tags: ['cloud', 'sun', 'rain'] },
  { name: 'Cloudy', Icon: Cloudy, tags: ['cloudy'] },
  { name: 'Club', Icon: Club, tags: ['club'] },
  { name: 'CodeSquare', Icon: CodeSquare, tags: ['code', 'square'] },
  { name: 'Codesandbox', Icon: Codesandbox, tags: ['codesandbox'] },
  { name: 'Columns', Icon: Columns, tags: ['columns'] },
  { name: 'Columns3', Icon: Columns3, tags: ['columns3'] },
  { name: 'Columns4', Icon: Columns4, tags: ['columns4'] },
  { name: 'Combine', Icon: Combine, tags: ['combine'] },
  { name: 'Command', Icon: Command, tags: ['command'] },
  { name: 'Component', Icon: Component, tags: ['component'] },
  { name: 'Computer', Icon: Computer, tags: ['computer'] },
  { name: 'ConciergeBell', Icon: ConciergeBell, tags: ['concierge', 'bell'] },
  { name: 'Cone', Icon: Cone, tags: ['cone'] },
  { name: 'Contact2', Icon: Contact2, tags: ['contact2'] },
  { name: 'Container', Icon: Container, tags: ['container'] },
  { name: 'Contrast', Icon: Contrast, tags: ['contrast'] },
  { name: 'Copy', Icon: Copy, tags: ['copy'] },
  { name: 'CopyCheck', Icon: CopyCheck, tags: ['copy', 'check'] },
  { name: 'CopyMinus', Icon: CopyMinus, tags: ['copy', 'minus'] },
  { name: 'CopyPlus', Icon: CopyPlus, tags: ['copy', 'plus'] },
  { name: 'CopySlash', Icon: CopySlash, tags: ['copy', 'slash'] },
  { name: 'CopyX', Icon: CopyX, tags: ['copy'] },
  { name: 'Copyleft', Icon: Copyleft, tags: ['copyleft'] },
  { name: 'Copyright', Icon: Copyright, tags: ['copyright'] },
  { name: 'CornerDownLeft', Icon: CornerDownLeft, tags: ['corner', 'down', 'left'] },
  { name: 'CornerDownRight', Icon: CornerDownRight, tags: ['corner', 'down', 'right'] },
  { name: 'CornerLeftDown', Icon: CornerLeftDown, tags: ['corner', 'left', 'down'] },
  { name: 'CornerLeftUp', Icon: CornerLeftUp, tags: ['corner', 'left'] },
  { name: 'CornerRightDown', Icon: CornerRightDown, tags: ['corner', 'right', 'down'] },
  { name: 'CornerRightUp', Icon: CornerRightUp, tags: ['corner', 'right'] },
  { name: 'CreativeCommons', Icon: CreativeCommons, tags: ['creative', 'commons'] },
  { name: 'Crop', Icon: Crop, tags: ['crop'] },
  { name: 'Cuboid', Icon: Cuboid, tags: ['cuboid'] },
  { name: 'Currency', Icon: Currency, tags: ['currency'] },
  { name: 'Cylinder', Icon: Cylinder, tags: ['cylinder'] },
  { name: 'Dam', Icon: Dam, tags: ['dam'] },
  { name: 'DatabaseBackup', Icon: DatabaseBackup, tags: ['database', 'backup'] },
  { name: 'DatabaseZap', Icon: DatabaseZap, tags: ['database', 'zap'] },
  { name: 'Delete', Icon: Delete, tags: ['delete'] },
  { name: 'Dessert', Icon: Dessert, tags: ['dessert'] },
  { name: 'Diameter', Icon: Diameter, tags: ['diameter'] },
  { name: 'DiamondMinus', Icon: DiamondMinus, tags: ['diamond', 'minus'] },
  { name: 'DiamondPercent', Icon: DiamondPercent, tags: ['diamond', 'percent'] },
  { name: 'DiamondPlus', Icon: DiamondPlus, tags: ['diamond', 'plus'] },
  { name: 'Dice1', Icon: Dice1, tags: ['dice1'] },
  { name: 'Dice2', Icon: Dice2, tags: ['dice2'] },
  { name: 'Dice3', Icon: Dice3, tags: ['dice3'] },
  { name: 'Dice4', Icon: Dice4, tags: ['dice4'] },
  { name: 'Dice5', Icon: Dice5, tags: ['dice5'] },
  { name: 'Dice6', Icon: Dice6, tags: ['dice6'] },
  { name: 'Dices', Icon: Dices, tags: ['dices'] },
  { name: 'Diff', Icon: Diff, tags: ['diff'] },
  { name: 'Disc2', Icon: Disc2, tags: ['disc2'] },
  { name: 'DiscAlbum', Icon: DiscAlbum, tags: ['disc', 'album'] },
  { name: 'Divide', Icon: Divide, tags: ['divide'] },
  { name: 'DivideSquare', Icon: DivideSquare, tags: ['divide', 'square'] },
  { name: 'DnaOff', Icon: DnaOff, tags: ['dna', 'off'] },
  { name: 'Dock', Icon: Dock, tags: ['dock'] },
  { name: 'Dot', Icon: Dot, tags: ['dot'] },
  { name: 'DotSquare', Icon: DotSquare, tags: ['dot', 'square'] },
  { name: 'Download', Icon: Download, tags: ['download'] },
  { name: 'DraftingCompass', Icon: DraftingCompass, tags: ['drafting', 'compass'] },
  { name: 'Dribbble', Icon: Dribbble, tags: ['dribbble'] },
  { name: 'Earth', Icon: Earth, tags: ['earth'] },
  { name: 'EarthLock', Icon: EarthLock, tags: ['earth', 'lock'] },
  { name: 'Edit', Icon: Edit, tags: ['edit'] },
  { name: 'Edit2', Icon: Edit2, tags: ['edit2'] },
  { name: 'Edit3', Icon: Edit3, tags: ['edit3'] },
  { name: 'EggFried', Icon: EggFried, tags: ['egg', 'fried'] },
  { name: 'EggOff', Icon: EggOff, tags: ['egg', 'off'] },
  { name: 'Ellipsis', Icon: Ellipsis, tags: ['ellipsis'] },
  { name: 'EllipsisVertical', Icon: EllipsisVertical, tags: ['ellipsis', 'vertical'] },
  { name: 'Equal', Icon: Equal, tags: ['equal'] },
  { name: 'EqualApproximately', Icon: EqualApproximately, tags: ['equal', 'approximately'] },
  { name: 'EqualNot', Icon: EqualNot, tags: ['equal', 'not'] },
  { name: 'EqualSquare', Icon: EqualSquare, tags: ['equal', 'square'] },
  { name: 'EthernetPort', Icon: EthernetPort, tags: ['ethernet', 'port'] },
  { name: 'Expand', Icon: Expand, tags: ['expand'] },
  { name: 'ExternalLink', Icon: ExternalLink, tags: ['external', 'link'] },
  { name: 'EyeClosed', Icon: EyeClosed, tags: ['eye', 'closed'] },
  { name: 'Facebook', Icon: Facebook, tags: ['facebook'] },
  { name: 'Factory', Icon: Factory, tags: ['factory'] },
  { name: 'Fan', Icon: Fan, tags: ['fan'] },
  { name: 'FastForward', Icon: FastForward, tags: ['fast', 'forward'] },
  { name: 'Fence', Icon: Fence, tags: ['fence'] },
  { name: 'FerrisWheel', Icon: FerrisWheel, tags: ['ferris', 'wheel'] },
  { name: 'Figma', Icon: Figma, tags: ['figma'] },
  { name: 'FileArchive', Icon: FileArchive, tags: ['file', 'archive'] },
  { name: 'FileAudio2', Icon: FileAudio2, tags: ['file', 'audio2'] },
  { name: 'FileAxis3D', Icon: FileAxis3D, tags: ['file', 'axis3d'] },
  { name: 'FileBadge', Icon: FileBadge, tags: ['file', 'badge'] },
  { name: 'FileBadge2', Icon: FileBadge2, tags: ['file', 'badge2'] },
  { name: 'FileBarChart', Icon: FileBarChart, tags: ['file', 'bar', 'chart'] },
  { name: 'FileBarChart2', Icon: FileBarChart2, tags: ['file', 'bar', 'chart2'] },
  { name: 'FileBox', Icon: FileBox, tags: ['file', 'box'] },
  { name: 'FileChartLine', Icon: FileChartLine, tags: ['file', 'chart', 'line'] },
  { name: 'FileChartPie', Icon: FileChartPie, tags: ['file', 'chart', 'pie'] },
  { name: 'FileCheck2', Icon: FileCheck2, tags: ['file', 'check2'] },
  { name: 'FileClock', Icon: FileClock, tags: ['file', 'clock'] },
  { name: 'FileCode2', Icon: FileCode2, tags: ['file', 'code2'] },
  { name: 'FileCog', Icon: FileCog, tags: ['file', 'cog'] },
  { name: 'FileDiff', Icon: FileDiff, tags: ['file', 'diff'] },
  { name: 'FileDigit', Icon: FileDigit, tags: ['file', 'digit'] },
  { name: 'FileDown', Icon: FileDown, tags: ['file', 'down'] },
  { name: 'FileEdit', Icon: FileEdit, tags: ['file', 'edit'] },
  { name: 'FileInput', Icon: FileInput, tags: ['file', 'input'] },
  { name: 'FileJson', Icon: FileJson, tags: ['file', 'json'] },
  { name: 'FileJson2', Icon: FileJson2, tags: ['file', 'json2'] },
  { name: 'FileKey', Icon: FileKey, tags: ['file', 'key'] },
  { name: 'FileKey2', Icon: FileKey2, tags: ['file', 'key2'] },
  { name: 'FileLock2', Icon: FileLock2, tags: ['file', 'lock2'] },
  { name: 'FileMinus2', Icon: FileMinus2, tags: ['file', 'minus2'] },
  { name: 'FileMusic', Icon: FileMusic, tags: ['file', 'music'] },
  { name: 'FileOutput', Icon: FileOutput, tags: ['file', 'output'] },
  { name: 'FilePenLine', Icon: FilePenLine, tags: ['file', 'pen', 'line'] },
  { name: 'FilePlus2', Icon: FilePlus2, tags: ['file', 'plus2'] },
  { name: 'FileQuestion', Icon: FileQuestion, tags: ['file', 'question'] },
  { name: 'FileScan', Icon: FileScan, tags: ['file', 'scan'] },
  { name: 'FileSearch2', Icon: FileSearch2, tags: ['file', 'search2'] },
  { name: 'FileSliders', Icon: FileSliders, tags: ['file', 'sliders'] },
  { name: 'FileStack', Icon: FileStack, tags: ['file', 'stack'] },
  { name: 'FileSymlink', Icon: FileSymlink, tags: ['file', 'symlink'] },
  { name: 'FileTerminal', Icon: FileTerminal, tags: ['file', 'terminal'] },
  { name: 'FileType', Icon: FileType, tags: ['file', 'type'] },
  { name: 'FileType2', Icon: FileType2, tags: ['file', 'type2'] },
  { name: 'FileUp', Icon: FileUp, tags: ['file'] },
  { name: 'FileUser', Icon: FileUser, tags: ['file', 'user'] },
  { name: 'FileVideo2', Icon: FileVideo2, tags: ['file', 'video2'] },
  { name: 'FileVolume', Icon: FileVolume, tags: ['file', 'volume'] },
  { name: 'FileVolume2', Icon: FileVolume2, tags: ['file', 'volume2'] },
  { name: 'FileX2', Icon: FileX2, tags: ['file'] },
  { name: 'Filter', Icon: Filter, tags: ['filter'] },
  { name: 'FilterX', Icon: FilterX, tags: ['filter'] },
  { name: 'FireExtinguisher', Icon: FireExtinguisher, tags: ['fire', 'extinguisher'] },
  { name: 'FishOff', Icon: FishOff, tags: ['fish', 'off'] },
  { name: 'FishSymbol', Icon: FishSymbol, tags: ['fish', 'symbol'] },
  { name: 'FlagOff', Icon: FlagOff, tags: ['flag', 'off'] },
  { name: 'FlagTriangleLeft', Icon: FlagTriangleLeft, tags: ['flag', 'triangle', 'left'] },
  { name: 'FlagTriangleRight', Icon: FlagTriangleRight, tags: ['flag', 'triangle', 'right'] },
  { name: 'FlameKindling', Icon: FlameKindling, tags: ['flame', 'kindling'] },
  { name: 'Flashlight', Icon: Flashlight, tags: ['flashlight'] },
  { name: 'FlashlightOff', Icon: FlashlightOff, tags: ['flashlight', 'off'] },
  { name: 'FlaskConicalOff', Icon: FlaskConicalOff, tags: ['flask', 'conical', 'off'] },
  { name: 'FlaskRound', Icon: FlaskRound, tags: ['flask', 'round'] },
  { name: 'FlipHorizontal2', Icon: FlipHorizontal2, tags: ['flip', 'horizontal2'] },
  { name: 'FlipVertical2', Icon: FlipVertical2, tags: ['flip', 'vertical2'] },
  { name: 'FoldHorizontal', Icon: FoldHorizontal, tags: ['fold', 'horizontal'] },
  { name: 'FoldVertical', Icon: FoldVertical, tags: ['fold', 'vertical'] },
  { name: 'FolderCheck', Icon: FolderCheck, tags: ['folder', 'check'] },
  { name: 'FolderClock', Icon: FolderClock, tags: ['folder', 'clock'] },
  { name: 'FolderClosed', Icon: FolderClosed, tags: ['folder', 'closed'] },
  { name: 'FolderCode', Icon: FolderCode, tags: ['folder', 'code'] },
  { name: 'FolderCog', Icon: FolderCog, tags: ['folder', 'cog'] },
  { name: 'FolderDot', Icon: FolderDot, tags: ['folder', 'dot'] },
  { name: 'FolderDown', Icon: FolderDown, tags: ['folder', 'down'] },
  { name: 'FolderEdit', Icon: FolderEdit, tags: ['folder', 'edit'] },
  { name: 'FolderGit', Icon: FolderGit, tags: ['folder', 'git'] },
  { name: 'FolderGit2', Icon: FolderGit2, tags: ['folder', 'git2'] },
  { name: 'FolderInput', Icon: FolderInput, tags: ['folder', 'input'] },
  { name: 'FolderKanban', Icon: FolderKanban, tags: ['folder', 'kanban'] },
  { name: 'FolderKey', Icon: FolderKey, tags: ['folder', 'key'] },
  { name: 'FolderMinus', Icon: FolderMinus, tags: ['folder', 'minus'] },
  { name: 'FolderOpenDot', Icon: FolderOpenDot, tags: ['folder', 'open', 'dot'] },
  { name: 'FolderOutput', Icon: FolderOutput, tags: ['folder', 'output'] },
  { name: 'FolderRoot', Icon: FolderRoot, tags: ['folder', 'root'] },
  { name: 'FolderSearch2', Icon: FolderSearch2, tags: ['folder', 'search2'] },
  { name: 'FolderSymlink', Icon: FolderSymlink, tags: ['folder', 'symlink'] },
  { name: 'FolderSync', Icon: FolderSync, tags: ['folder', 'sync'] },
  { name: 'FolderUp', Icon: FolderUp, tags: ['folder'] },
  { name: 'FolderX', Icon: FolderX, tags: ['folder'] },
  { name: 'Folders', Icon: Folders, tags: ['folders'] },
  { name: 'ForkKnife', Icon: ForkKnife, tags: ['fork', 'knife'] },
  { name: 'ForkKnifeCrossed', Icon: ForkKnifeCrossed, tags: ['fork', 'knife', 'crossed'] },
  { name: 'Forklift', Icon: Forklift, tags: ['forklift'] },
  { name: 'FormInput', Icon: FormInput, tags: ['form', 'input'] },
  { name: 'Frame', Icon: Frame, tags: ['frame'] },
  { name: 'Framer', Icon: Framer, tags: ['framer'] },
  { name: 'Fullscreen', Icon: Fullscreen, tags: ['fullscreen'] },
  { name: 'FunctionSquare', Icon: FunctionSquare, tags: ['function', 'square'] },
  { name: 'GalleryHorizontal', Icon: GalleryHorizontal, tags: ['gallery', 'horizontal'] },
  { name: 'GalleryHorizontalEnd', Icon: GalleryHorizontalEnd, tags: ['gallery', 'horizontal', 'end'] },
];

const BY_NAME = new Map<string, IconEntry>(ENTRIES.map(e => [e.name, e]));

export const ICON_LIBRARY: ReadonlyArray<IconEntry> = ENTRIES;

/** Lookup an icon component by stored name. Returns null when not found. */
export function getIconByName(name: string | null | undefined): LucideIcon | null {
  if (!name) return null;
  return BY_NAME.get(name)?.Icon ?? null;
}

/** Free-text search across name + tags. Returns matching entries, max `limit`. */
export function searchIcons(query: string, limit = 200): IconEntry[] {
  const q = query.trim().toLowerCase();
  if (!q) return ENTRIES.slice(0, limit);
  const out: IconEntry[] = [];
  for (const e of ENTRIES) {
    const haystack = `${e.name.toLowerCase()} ${e.tags.join(' ')}`;
    if (haystack.includes(q)) out.push(e);
    if (out.length >= limit) break;
  }
  return out;
}

/**
 * Suggest icons that fit the given freeform text (task title, tag label, etc.).
 * Returns up to `limit` entries ranked by token-overlap with names + tags.
 */
export function suggestIcons(text: string, limit = 6): IconEntry[] {
  const tokens = text
    .toLowerCase()
    .split(/[^a-z0-9]+/)
    .filter(t => t.length >= 3);
  if (tokens.length === 0) return [];

  const scored: { entry: IconEntry; score: number }[] = [];
  for (const entry of ENTRIES) {
    const nameLower = entry.name.toLowerCase();
    let score = 0;
    for (const tok of tokens) {
      // Exact tag match is strongest
      if (entry.tags.includes(tok)) score += 5;
      // Substring match in any tag
      else if (entry.tags.some(tag => tag.includes(tok) || tok.includes(tag))) score += 3;
      // Name match
      if (nameLower === tok) score += 4;
      else if (nameLower.includes(tok)) score += 2;
    }
    if (score > 0) scored.push({ entry, score });
  }
  scored.sort((a, b) => b.score - a.score);
  return scored.slice(0, limit).map(s => s.entry);
}
